"use client";

import { ImagePreviewUploader } from "@/components/baby/image-preview-uploader";
import { format, useLocale } from "@/components/i18n/locale-provider";
import type { Dictionary } from "@/lib/i18n/dictionary";
import type { BabyProfile, CaregiverPermission } from "@/types/baby";
import { ChevronLeft, X } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";

const permissions: CaregiverPermission[] = ["Full access", "View and add activities", "View only"];

type InputProps = { label: string; value: string; onChange: (value: string) => void; type?: string; wide?: boolean };
function Input({ label, value, onChange, type = "text", wide }: InputProps) { return <label className={`profile-form__field${wide ? " profile-form__field--full" : ""}`}><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Select({ label, value, onChange, options }: InputProps & { options: string[] }) { return <label className="profile-form__field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Textarea({ label, value, onChange }: InputProps) { return <label className="profile-form__field profile-form__field--full"><span>{label}</span><textarea rows={3} value={value} onChange={(event) => onChange(event.target.value)} /></label>; }
function Toggle({ label, value, onChange, yes, no }: { label: string; value: boolean; onChange: (value: boolean) => void; yes: string; no: string }) { return <fieldset className="profile-form__toggle"><legend>{label}</legend><button type="button" className={!value ? "profile-form__toggle-option profile-form__toggle-option--active" : "profile-form__toggle-option"} onClick={() => onChange(false)} aria-pressed={!value}>{no}</button><button type="button" className={value ? "profile-form__toggle-option profile-form__toggle-option--active" : "profile-form__toggle-option"} onClick={() => onChange(true)} aria-pressed={value}>{yes}</button></fieldset>; }

export function EditBabyProfileFlow({ profile, onCancel, onSave }: { profile: BabyProfile; onCancel: () => void; onSave: (profile: BabyProfile) => void }) {
  const { t } = useLocale();
  const dict = t((d) => d.baby);
  const editDict = t((d) => d.baby.editFlow);
  const fieldsDict = t((d) => d.baby.fields);
  const steps = [editDict.steps.basicInfo, editDict.steps.birthAndGrowth, editDict.steps.feeding, editDict.steps.health, editDict.steps.routineAndCaregivers];
  const [draft, setDraft] = useState(profile);
  const [step, setStep] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [confirmDiscard, setConfirmDiscard] = useState(false);
  const dirty = useMemo(() => JSON.stringify(draft) !== JSON.stringify(profile), [draft, profile]);
  const set = <K extends keyof BabyProfile>(key: K, value: BabyProfile[K]) => setDraft((current) => ({ ...current, [key]: value }));
  const setGrowth = (key: "birthGrowth" | "currentGrowth", field: keyof BabyProfile["birthGrowth"], value: string) => setDraft((current) => ({ ...current, [key]: { ...current[key], [field]: value } }));
  const setFeeding = (field: keyof BabyProfile["feeding"], value: string) => setDraft((current) => ({ ...current, feeding: { ...current.feeding, [field]: value } }));
  const setHealth = (field: keyof BabyProfile["health"], value: string) => setDraft((current) => ({ ...current, health: { ...current.health, [field]: value } }));
  const setRoutine = (field: keyof BabyProfile["routine"], value: string) => setDraft((current) => ({ ...current, routine: { ...current.routine, [field]: value } }));
  const validStep = () => { const invalid = step === 0 ? !draft.fullName.trim() || !draft.preferredName.trim() || !draft.dateOfBirth : step === 1 ? !draft.birthGrowth.weightKg || !draft.currentGrowth.weightKg : false; if (invalid) { setError(editDict.validationError); return false; } setError(null); return true; };
  const requestCancel = () => { if (dirty) setConfirmDiscard(true); else onCancel(); };
  const next = () => { if (!validStep()) return; if (step === steps.length - 1) onSave(draft); else setStep((current) => current + 1); };
  const basic = <div className="profile-form"><ImagePreviewUploader name={draft.preferredName} value={draft.photoPreview} onChange={(photoPreview) => set("photoPreview", photoPreview)} /><div className="profile-form__grid"><Input label={fieldsDict.fullName} value={draft.fullName} onChange={(value) => set("fullName", value)} /><Input label={fieldsDict.preferredName} value={draft.preferredName} onChange={(value) => set("preferredName", value)} /><Input label={fieldsDict.dateOfBirth} type="date" value={draft.dateOfBirth} onChange={(value) => set("dateOfBirth", value)} /><Input label={fieldsDict.timeOfBirth} type="time" value={draft.timeOfBirth} onChange={(value) => set("timeOfBirth", value)} /><Select label={fieldsDict.sex} value={draft.sex} onChange={(value) => set("sex", value as BabyProfile["sex"])} options={["Female", "Male", "Prefer not to say"]} /><Select label={fieldsDict.birthType} value={draft.birthType} onChange={(value) => set("birthType", value as BabyProfile["birthType"])} options={["Natural birth", "C-section", "Assisted birth"]} /><Toggle label={fieldsDict.prematureBirth} value={draft.premature} onChange={(value) => set("premature", value)} yes={dict.yes} no={dict.no} /><Input label={fieldsDict.gestationalAge} value={draft.gestationalAge} onChange={(value) => set("gestationalAge", value)} /><Input label={fieldsDict.birthHospital} value={draft.birthHospital} onChange={(value) => set("birthHospital", value)} /><Input label={fieldsDict.birthCountry} value={draft.birthCountry} onChange={(value) => set("birthCountry", value)} /></div></div>;
  const growth = <div className="profile-form"><h4>{editDict.growthAtBirthHeading}</h4><div className="profile-form__grid"><Input label={editDict.birthWeightKg} type="number" value={draft.birthGrowth.weightKg} onChange={(value) => setGrowth("birthGrowth", "weightKg", value)} /><Input label={editDict.birthLengthCm} type="number" value={draft.birthGrowth.lengthCm} onChange={(value) => setGrowth("birthGrowth", "lengthCm", value)} /><Input label={editDict.headCircumferenceCm} type="number" value={draft.birthGrowth.headCircumferenceCm} onChange={(value) => setGrowth("birthGrowth", "headCircumferenceCm", value)} /></div><h4>{editDict.currentGrowthHeading}</h4><div className="profile-form__grid"><Input label={editDict.currentWeightKg} type="number" value={draft.currentGrowth.weightKg} onChange={(value) => setGrowth("currentGrowth", "weightKg", value)} /><Input label={editDict.currentLengthCm} type="number" value={draft.currentGrowth.lengthCm} onChange={(value) => setGrowth("currentGrowth", "lengthCm", value)} /><Input label={editDict.headCircumferenceCm} type="number" value={draft.currentGrowth.headCircumferenceCm} onChange={(value) => setGrowth("currentGrowth", "headCircumferenceCm", value)} /><Input label={editDict.lastUpdated} value={draft.currentGrowth.updatedAt} onChange={(value) => setGrowth("currentGrowth", "updatedAt", value)} /></div></div>;
  const feeding = <div className="profile-form"><div className="profile-form__grid"><Select label={editDict.mainFeedingMethod} value={draft.feeding.mainMethod} onChange={(value) => setFeeding("mainMethod", value)} options={["Breastfeeding", "Formula feeding", "Mixed feeding"]} /><Select label={editDict.breastfeeding} value={draft.feeding.breastfeeding} onChange={(value) => setFeeding("breastfeeding", value)} options={["Yes", "No"]} /><Select label={editDict.formulaFeeding} value={draft.feeding.formulaFeeding} onChange={(value) => setFeeding("formulaFeeding", value)} options={["Yes", "No"]} /><Select label={editDict.mixedFeeding} value={draft.feeding.mixedFeeding} onChange={(value) => setFeeding("mixedFeeding", value)} options={["Yes", "No"]} /><Input label={fieldsDict.formulaBrand} value={draft.feeding.formulaBrand} onChange={(value) => setFeeding("formulaBrand", value)} /><Input label={fieldsDict.formulaType} value={draft.feeding.formulaType} onChange={(value) => setFeeding("formulaType", value)} /><Input label={editDict.typicalBottleAmountMl} type="number" value={draft.feeding.typicalBottleAmount} onChange={(value) => setFeeding("typicalBottleAmount", value)} /><Textarea label={fieldsDict.knownFeedingDifficulties} value={draft.feeding.difficulties} onChange={(value) => setFeeding("difficulties", value)} /></div></div>;
  const health = <div className="profile-form"><div className="profile-form__grid"><Input label={fieldsDict.bloodType} value={draft.health.bloodType} onChange={(value) => setHealth("bloodType", value)} /><Input label={fieldsDict.knownAllergies} value={draft.health.allergies} onChange={(value) => setHealth("allergies", value)} /><Input label={fieldsDict.medicalConditions} value={draft.health.conditions} onChange={(value) => setHealth("conditions", value)} /><Input label={fieldsDict.currentMedicines} value={draft.health.medicines} onChange={(value) => setHealth("medicines", value)} /><Input label={editDict.pediatricianName} value={draft.health.pediatricianName} onChange={(value) => setHealth("pediatricianName", value)} /><Input label={fieldsDict.pediatricianPhone} value={draft.health.pediatricianPhone} onChange={(value) => setHealth("pediatricianPhone", value)} /><Textarea label={fieldsDict.emergencyNotes} value={draft.health.emergencyNotes} onChange={(value) => setHealth("emergencyNotes", value)} /></div></div>;
  const routine = <div className="profile-form"><div className="profile-form__grid"><Input label={editDict.typicalWakeUpTime} type="time" value={draft.routine.wakeUpTime} onChange={(value) => setRoutine("wakeUpTime", value)} /><Input label={fieldsDict.typicalBedtime} type="time" value={draft.routine.bedtime} onChange={(value) => setRoutine("bedtime", value)} /><Input label={editDict.typicalFeedingInterval} value={draft.routine.feedingInterval} onChange={(value) => setRoutine("feedingInterval", value)} /><Input label={fieldsDict.preferredSleepSound} value={draft.routine.preferredSleepSound} onChange={(value) => setRoutine("preferredSleepSound", value)} /><Textarea label={editDict.notesAboutCalming} value={draft.routine.calmingNotes} onChange={(value) => setRoutine("calmingNotes", value)} /></div><h4>{editDict.caregiversHeading}</h4><div className="caregiver-editor">{draft.caregivers.map((caregiver) => <div key={caregiver.id}><strong>{caregiver.relationship}</strong><Input label={editDict.name} value={caregiver.name} onChange={(value) => set("caregivers", draft.caregivers.map((item) => item.id === caregiver.id ? { ...item, name: value } : item))} /><Input label={editDict.phone} value={caregiver.phone} onChange={(value) => set("caregivers", draft.caregivers.map((item) => item.id === caregiver.id ? { ...item, phone: value } : item))} /><Select label={editDict.permission} value={caregiver.permission} onChange={(value) => set("caregivers", draft.caregivers.map((item) => item.id === caregiver.id ? { ...item, permission: value as CaregiverPermission } : item))} options={permissions} /></div>)}</div></div>;
  const content = [basic, growth, feeding, health, routine][step];
  return <div className="profile-flow-layer"><button className="profile-flow-layer__overlay" type="button" aria-label={editDict.closeLabel} onClick={requestCancel} /><section className="profile-flow" role="dialog" aria-modal="true" aria-labelledby="profile-flow-title"><header><div><p>{profile.preferredName}{dict.hero.subtitle}</p><h2 id="profile-flow-title">{editDict.editTitle}</h2></div><button type="button" className="icon-button icon-button--soft" onClick={requestCancel} aria-label={editDict.closeLabel}><X size={20} aria-hidden="true" /></button></header><ProfileStepIndicator step={step} steps={steps} stepAriaTemplate={editDict.stepAria} /><form onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); next(); }}><div className="profile-flow__content"><h3>{steps[step]}</h3>{content}{error ? <p className="profile-form__error" role="alert">{error}</p> : null}</div><footer><button type="button" className="button button--secondary" onClick={step ? () => setStep((current) => current - 1) : requestCancel}>{step ? <><ChevronLeft size={16} aria-hidden="true" />{editDict.back}</> : editDict.cancel}</button><button type="submit" className="button button--primary">{step === steps.length - 1 ? editDict.saveProfile : editDict.continueButton}</button></footer></form></section>{confirmDiscard ? <UnsavedChangesDialog name={draft.preferredName} dict={editDict.unsavedChanges} onCancel={() => setConfirmDiscard(false)} onDiscard={onCancel} /> : null}</div>;
}

export function ProfileStepIndicator({ step, steps, stepAriaTemplate }: { step: number; steps: string[]; stepAriaTemplate: string }) { return <div className="profile-step-indicator" aria-label={format(stepAriaTemplate, { step: String(step + 1), total: String(steps.length) })}>{steps.map((label, index) => <span key={label} className={index <= step ? "profile-step-indicator__item profile-step-indicator__item--active" : "profile-step-indicator__item"}><i>{index + 1}</i><b>{label}</b></span>)}</div>; }
function UnsavedChangesDialog({ name, dict, onCancel, onDiscard }: { name: string; dict: Dictionary["baby"]["editFlow"]["unsavedChanges"]; onCancel: () => void; onDiscard: () => void }) { return <div className="dialog-layer"><button type="button" className="dialog-layer__overlay" aria-label="Close discard confirmation" onClick={onCancel} /><section className="confirm-dialog" role="dialog" aria-modal="true"><p>{dict.eyebrow}</p><h2>{dict.title}</h2><span>{format(dict.bodyTemplate, { name })}</span><div><button type="button" className="button button--secondary" onClick={onCancel}>{dict.keepEditing}</button><button type="button" className="button button--danger" onClick={onDiscard}>{dict.discard}</button></div></section></div>; }
