export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type Table<Row, Insert, Update> = { Row: Row; Insert: Insert; Update: Update; Relationships: [] };
type ActivityRow = { id: string; baby_id: string; created_by: string | null; created_at: string; updated_at: string };
type ActivityInsert = { id?: string; baby_id: string; created_by?: string | null; created_at?: string; updated_at?: string };
type ActivityUpdate = Partial<ActivityInsert>;

export type ProfileRow = { id: string; display_name: string | null; first_name: string | null; last_name: string | null; avatar_url: string | null; preferred_language: string; timezone: string; onboarding_completed: boolean; created_at: string; updated_at: string };
export type FamilyRow = { id: string; name: string; owner_id: string; invite_code: string; created_at: string; updated_at: string };
export type BabyRow = { id: string; family_id: string; first_name: string; last_name: string | null; nickname: string | null; date_of_birth: string | null; due_date: string | null; biological_sex: "female" | "male" | "intersex" | "not_specified" | null; birth_weight_grams: number | null; birth_length_cm: number | null; avatar_url: string | null; notes: string | null; is_active: boolean; created_at: string; updated_at: string };

export type Database = { public: { Tables: {
  profiles: Table<ProfileRow, { id: string; display_name?: string | null; first_name?: string | null; last_name?: string | null; avatar_url?: string | null; preferred_language?: string; timezone?: string; onboarding_completed?: boolean }, Partial<Omit<ProfileRow, "id" | "created_at" | "updated_at">>>;
  families: Table<FamilyRow, { id?: string; name: string; owner_id: string; invite_code?: string }, Partial<Pick<FamilyRow, "name" | "invite_code">>>;
  family_members: Table<{ id: string; family_id: string; user_id: string; role: "owner" | "parent" | "caregiver"; status: "invited" | "active" | "removed"; joined_at: string | null; created_at: string }, { id?: string; family_id: string; user_id: string; role?: "owner" | "parent" | "caregiver"; status?: "invited" | "active" | "removed"; joined_at?: string | null }, { role?: "owner" | "parent" | "caregiver"; status?: "invited" | "active" | "removed"; joined_at?: string | null }>;
  babies: Table<BabyRow, { id?: string; family_id: string; first_name: string; last_name?: string | null; nickname?: string | null; date_of_birth?: string | null; due_date?: string | null; biological_sex?: "female" | "male" | "intersex" | "not_specified" | null; birth_weight_grams?: number | null; birth_length_cm?: number | null; avatar_url?: string | null; notes?: string | null; is_active?: boolean }, Partial<Omit<BabyRow, "id" | "family_id" | "created_at" | "updated_at">>>;
  feeding_logs: Table<ActivityRow & { feeding_type: "breastfeeding" | "bottle" | "formula" | "pumped_milk" | "solid_food" | "water" | "custom"; started_at: string; ended_at: string | null; duration_minutes: number | null; breast_side: "left" | "right" | "both" | null; amount_ml: number | null; food_name: string | null; notes: string | null }, ActivityInsert & { feeding_type: "breastfeeding" | "bottle" | "formula" | "pumped_milk" | "solid_food" | "water" | "custom"; started_at: string; ended_at?: string | null; duration_minutes?: number | null; breast_side?: "left" | "right" | "both" | null; amount_ml?: number | null; food_name?: string | null; notes?: string | null }, ActivityUpdate>;
  sleep_logs: Table<ActivityRow & { started_at: string; ended_at: string | null; duration_minutes: number | null; sleep_type: "nap" | "night_sleep" | "custom"; sleep_location: string | null; quality: "restless" | "fair" | "good" | "unknown" | null; notes: string | null }, ActivityInsert & { started_at: string; ended_at?: string | null; duration_minutes?: number | null; sleep_type?: "nap" | "night_sleep" | "custom"; sleep_location?: string | null; quality?: "restless" | "fair" | "good" | "unknown" | null; notes?: string | null }, ActivityUpdate>;
  diaper_logs: Table<ActivityRow & { logged_at: string; diaper_type: "wet" | "dirty" | "mixed" | "dry" | "other"; stool_color: string | null; stool_consistency: string | null; notes: string | null }, ActivityInsert & { logged_at?: string; diaper_type: "wet" | "dirty" | "mixed" | "dry" | "other"; stool_color?: string | null; stool_consistency?: string | null; notes?: string | null }, ActivityUpdate>;
  growth_logs: Table<ActivityRow & { measured_at: string; weight_grams: number | null; height_cm: number | null; head_circumference_cm: number | null; notes: string | null }, ActivityInsert & { measured_at: string; weight_grams?: number | null; height_cm?: number | null; head_circumference_cm?: number | null; notes?: string | null }, ActivityUpdate>;
  milestones: Table<ActivityRow & { title: string; category: string; achieved_at: string | null; notes: string | null }, ActivityInsert & { title: string; category: string; achieved_at?: string | null; notes?: string | null }, ActivityUpdate>;
  vaccines: Table<ActivityRow & { vaccine_name: string; scheduled_date: string | null; administered_date: string | null; status: "scheduled" | "completed" | "postponed" | "skipped"; dose_label: string | null; healthcare_provider: string | null; notes: string | null }, ActivityInsert & { vaccine_name: string; scheduled_date?: string | null; administered_date?: string | null; status?: "scheduled" | "completed" | "postponed" | "skipped"; dose_label?: string | null; healthcare_provider?: string | null; notes?: string | null }, ActivityUpdate>;
  medicine_logs: Table<ActivityRow & { medicine_name: string; amount: number | null; unit: string | null; administered_at: string; prescribed_by: string | null; notes: string | null }, ActivityInsert & { medicine_name: string; amount?: number | null; unit?: string | null; administered_at: string; prescribed_by?: string | null; notes?: string | null }, ActivityUpdate>;
  memories: Table<ActivityRow & { memory_type: string; title: string; caption: string | null; notes: string | null; occurred_at: string; image_path: string | null; related_milestone_id: string | null; is_favorite: boolean }, ActivityInsert & { memory_type: string; title: string; caption?: string | null; notes?: string | null; occurred_at: string; image_path?: string | null; related_milestone_id?: string | null; is_favorite?: boolean }, ActivityUpdate>;
  journal_entries: Table<ActivityRow & { entry_date: string; activity_summary: string; parent_note: string | null; highlight: string | null }, ActivityInsert & { entry_date: string; activity_summary: string; parent_note?: string | null; highlight?: string | null }, ActivityUpdate>;
  article_bookmarks: Table<{ id: string; user_id: string; article_slug: string; created_at: string }, { id?: string; user_id: string; article_slug: string }, { article_slug?: string }>;
  article_feedback: Table<{ id: string; user_id: string; article_slug: string; was_helpful: boolean; created_at: string; updated_at: string }, { id?: string; user_id: string; article_slug: string; was_helpful: boolean }, { was_helpful?: boolean }>;
  ai_conversations: Table<{ id: string; user_id: string; baby_id: string | null; title: string | null; created_at: string; updated_at: string }, { id?: string; user_id: string; baby_id?: string | null; title?: string | null }, { baby_id?: string | null; title?: string | null }>;
  ai_messages: Table<{ id: string; conversation_id: string; role: "user" | "assistant" | "system"; content: string; created_at: string }, { id?: string; conversation_id: string; role: "user" | "assistant" | "system"; content: string }, { content?: string }>;
}; Views: Record<string, never>; Functions: { create_family: { Args: { family_name: string }; Returns: string } }; Enums: { family_role: "owner" | "parent" | "caregiver"; family_member_status: "invited" | "active" | "removed"; feeding_type: "breastfeeding" | "bottle" | "formula" | "pumped_milk" | "solid_food" | "water" | "custom"; sleep_type: "nap" | "night_sleep" | "custom"; vaccine_status: "scheduled" | "completed" | "postponed" | "skipped"; ai_message_role: "user" | "assistant" | "system" }; CompositeTypes: Record<string, never> } };
