"use client";
/* eslint-disable @next/next/no-img-element -- selected image URLs are local-only blob previews. */

import { useActivities } from "@/components/activity/activity-provider";
import { BabyAvatar } from "@/components/baby/baby-avatar";
import { useBabyProfile } from "@/components/baby/baby-profile-provider";
import { useDevelopment } from "@/components/development/development-provider";
import { PiluIllustration } from "@/components/illustrations/pilu-illustration";
import { useMemories } from "@/components/memory/memory-provider";
import { Toast } from "@/components/timeline/toast";
import { getBabyAge } from "@/lib/baby-data";
import { createDailyActivitySummary, createMonthlyRecap, filterMemories, formatMemoryDate, groupMemoriesByMonth, memoryTypeLabels, monthKey, monthLabel } from "@/lib/memory-data";
import type { JournalDraft, JournalEntry, Memory, MemoryDraft, MemoryFilter, MemoryType } from "@/types/memory";
import { BookOpen, CalendarDays, Camera, ChevronRight, Edit3, Heart, Images, LockKeyhole, Plus, Share2, Sparkles, Star, Trash2, Upload, X } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";

const filters: { id: MemoryFilter; label: string }[] = [{ id: "all", label: "All" }, { id: "favorites", label: "Favorites" }, { id: "milestones", label: "Milestones" }, { id: "photos", label: "Photos" }, { id: "firstMoments", label: "First moments" }];
const defaultDate = "2026-07-10";

export function MemoryBookDashboard() {
  const { memories, journalEntries, saveMemory, removeMemory, toggleFavorite, saveJournal, removeJournal } = useMemories();
  const { activities } = useActivities(); const { milestones } = useDevelopment(); const { profile } = useBabyProfile();
  const [filter, setFilter] = useState<MemoryFilter>("all"); const [editor, setEditor] = useState<Memory | null | "new">(null); const [selected, setSelected] = useState<Memory | null>(null); const [deleteTarget, setDeleteTarget] = useState<Memory | null>(null); const [journalEdit, setJournalEdit] = useState<JournalEntry | null | "new">(null); const [toast, setToast] = useState<string | null>(null);
  const visible = useMemo(() => filterMemories(memories, filter), [memories, filter]); const groups = useMemo(() => groupMemoriesByMonth(visible), [visible]);
  const recap = useMemo(() => createMonthlyRecap(memories, milestones.filter((milestone) => milestone.status === "achieved").length, journalEntries, profile.preferredName), [memories, milestones, journalEntries, profile.preferredName]);
  const todaySummary = createDailyActivitySummary(activities, memories.filter((memory) => memory.date === defaultDate).length, profile.preferredName);
  function announce(message: string) { setToast(message); window.setTimeout(() => setToast(null), 3200); }
  function save(draft: MemoryDraft, id?: string) { saveMemory(draft, id); setEditor(null); announce(id ? "Memory updated" : "Memory saved to your book"); }
  function remove() { if (!deleteTarget) return; removeMemory(deleteTarget.id); setDeleteTarget(null); setSelected(null); announce("Memory removed from this local session"); }
  return <div className="memory-book-page">
    <MemoryBookHeader memoryCount={memories.length} monthCount={memories.filter((memory) => monthKey(memory.date) === "2026-07").length} onAdd={() => setEditor("new")} profile={profile} />
    <MemoryFilterChips active={filter} onChange={setFilter} />
    {visible.length ? <div className="memory-months">{Object.entries(groups).map(([month, entries], index) => <MemoryMonthSection key={month} month={month} entries={entries} first={index === 0} onOpen={setSelected} onFavorite={(memory) => toggleFavorite(memory.id)} />)}</div> : <MemoryEmptyState filter={filter} onAdd={() => setEditor("new")} />}
    <DailyJournalCard summary={todaySummary} entry={journalEntries.find((entry) => entry.date === defaultDate)} onEdit={() => setJournalEdit(journalEntries.find((entry) => entry.date === defaultDate) ?? "new")} />
    <JournalHistory entries={journalEntries} onEdit={setJournalEdit} onDelete={(entry) => { removeJournal(entry.id); announce("Journal entry removed"); }} />
    <MonthlyRecapCard recap={recap} onComingSoon={() => announce("Sharing and album export are coming later.")} />
    {editor ? <AddMemoryFlow memory={editor === "new" ? undefined : editor} milestones={milestones} onClose={() => setEditor(null)} onSave={save} /> : null}
    {selected ? <MemoryDetailSheet memory={selected} onClose={() => setSelected(null)} onEdit={() => { setEditor(selected); setSelected(null); }} onDelete={() => setDeleteTarget(selected)} onFavorite={() => { toggleFavorite(selected.id); setSelected((current) => current ? { ...current, favorite: !current.favorite } : current); }} onComingSoon={() => announce("Sharing and album export are coming later.")} /> : null}
    {journalEdit ? <JournalEntryForm entry={journalEdit === "new" ? undefined : journalEdit} summary={todaySummary} onClose={() => setJournalEdit(null)} onSave={(draft, id) => { saveJournal(draft, id); setJournalEdit(null); announce(id ? "Journal entry updated" : "Today's journal saved"); }} /> : null}
    <ConfirmMemoryDelete open={Boolean(deleteTarget)} title={deleteTarget?.title ?? "this memory"} onCancel={() => setDeleteTarget(null)} onConfirm={remove} />
    <Toast message={toast} />
  </div>;
}

export function MemoryBookHeader({ memoryCount, monthCount, onAdd, profile }: { memoryCount: number; monthCount: number; onAdd: () => void; profile: { preferredName: string; dateOfBirth: string; photoPreview?: string } }) { return <header className="memory-book-header"><div className="memory-book-header__baby"><BabyAvatar name={profile.preferredName} photoPreview={profile.photoPreview} /><div><p>Memory Book</p><h1>{profile.preferredName}&apos;s little album</h1><span>{getBabyAge(profile.dateOfBirth)}</span></div></div><button type="button" className="memory-book-header__add button button--primary" onClick={onAdd}><Plus size={17} aria-hidden="true" />Add memory</button><div className="memory-book-header__metrics"><span><strong>{memoryCount}</strong>memories</span><span><strong>{monthCount}</strong>this month</span><span><Heart size={16} aria-hidden="true" />kept close</span></div></header>; }
export function MemoryFilterChips({ active, onChange }: { active: MemoryFilter; onChange: (filter: MemoryFilter) => void }) { return <div className="memory-filter-chips" role="tablist" aria-label="Filter memories">{filters.map((filter) => <button key={filter.id} type="button" role="tab" aria-selected={active === filter.id} className={active === filter.id ? "memory-filter-chips__button memory-filter-chips__button--active" : "memory-filter-chips__button"} onClick={() => onChange(filter.id)}>{filter.label}</button>)}</div>; }
export function MemoryMonthSection({ month, entries, first, onOpen, onFavorite }: { month: string; entries: Memory[]; first: boolean; onOpen: (memory: Memory) => void; onFavorite: (memory: Memory) => void }) { return <section className="memory-month-section"><header><div><p>{month === "2026-07" ? "This month" : first ? "Recent memories" : "Earlier"}</p><h2>{monthLabel(`${month}-01`)}</h2></div><span>{entries.length} saved</span></header><MemoryGrid entries={entries} onOpen={onOpen} onFavorite={onFavorite} /></section>; }
export function MemoryGrid({ entries, onOpen, onFavorite }: { entries: Memory[]; onOpen: (memory: Memory) => void; onFavorite: (memory: Memory) => void }) { return <div className="memory-grid">{entries.map((memory) => <MemoryCard key={memory.id} memory={memory} onOpen={() => onOpen(memory)} onFavorite={() => onFavorite(memory)} />)}</div>; }
export function MemoryCard({ memory, onOpen, onFavorite }: { memory: Memory; onOpen: () => void; onFavorite: () => void }) { return <article className="memory-card"><button type="button" className="memory-card__open" onClick={onOpen} aria-label={`Open memory: ${memory.title}`}><MemoryVisual memory={memory} compact /><div className="memory-card__content"><span>{memoryTypeLabels[memory.type]}</span><h3>{memory.title}</h3><p>{memory.caption || formatMemoryDate(memory.date)}</p><time>{formatMemoryDate(memory.date, memory.time)}</time></div></button><button type="button" className={memory.favorite ? "memory-card__favorite memory-card__favorite--active" : "memory-card__favorite"} aria-label={memory.favorite ? `Remove ${memory.title} from favorites` : `Add ${memory.title} to favorites`} aria-pressed={memory.favorite} onClick={onFavorite}><Heart size={16} fill={memory.favorite ? "currentColor" : "none"} aria-hidden="true" /></button></article>; }

function MemoryVisual({ memory, compact = false }: { memory: Memory; compact?: boolean }) { if (memory.imagePreview) return <img className={compact ? "memory-visual memory-visual--image" : "memory-detail__image"} src={memory.imagePreview} alt={memory.imageAlt || memory.title} />; return <div className={compact ? "memory-visual memory-visual--placeholder" : "memory-detail__illustration"}>{memory.type === "milestone" ? <Star size={compact ? 26 : 42} aria-hidden="true" /> : memory.type === "photo" ? <Camera size={compact ? 26 : 42} aria-hidden="true" /> : <PiluIllustration variant={memory.type === "dailyMoment" ? "sleeping-baby" : "teddy"} alt="" />}</div>; }

export function MemoryDetailSheet({ memory, onClose, onEdit, onDelete, onFavorite, onComingSoon }: { memory: Memory; onClose: () => void; onEdit: () => void; onDelete: () => void; onFavorite: () => void; onComingSoon: () => void }) { const closeButton = useRef<HTMLButtonElement>(null); useEffect(() => { closeButton.current?.focus(); const escape = (event: KeyboardEvent) => event.key === "Escape" && onClose(); window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [onClose]); return <div className="memory-sheet-layer"><button className="memory-sheet-layer__overlay" type="button" onClick={onClose} aria-label="Close memory detail" /><section className="memory-sheet memory-detail" role="dialog" aria-modal="true" aria-labelledby="memory-detail-title"><header><button ref={closeButton} type="button" onClick={onClose} aria-label="Close memory detail"><X size={20} /></button><span>Memory</span><button type="button" aria-label={memory.favorite ? "Remove from favorites" : "Add to favorites"} aria-pressed={memory.favorite} onClick={onFavorite}><Heart size={19} fill={memory.favorite ? "currentColor" : "none"} /></button></header><MemoryVisual memory={memory} /><div className="memory-detail__copy"><p>{memoryTypeLabels[memory.type]}</p><h2 id="memory-detail-title">{memory.title}</h2><time>{formatMemoryDate(memory.date, memory.time)}</time>{memory.caption ? <strong>{memory.caption}</strong> : null}{memory.note ? <span>{memory.note}</span> : null}{memory.milestoneName ? <Link href="/milestones" className="memory-detail__milestone"><Star size={16} aria-hidden="true" /><div><b>{memory.milestoneName}</b><small>{memory.milestoneCategory} · achieved {memory.achievedDate ? formatMemoryDate(memory.achievedDate) : ""}</small></div><ChevronRight size={16} aria-hidden="true" /></Link> : null}{memory.privateNote ? <small className="memory-detail__private"><LockKeyhole size={14} aria-hidden="true" />Private note</small> : null}</div><footer><button type="button" onClick={onComingSoon}><Share2 size={16} aria-hidden="true" />Share</button><button type="button" onClick={onEdit} disabled={memory.source === "milestone"}><Edit3 size={16} aria-hidden="true" />Edit</button><button type="button" onClick={onDelete} disabled={memory.source === "milestone"}><Trash2 size={16} aria-hidden="true" />Delete</button></footer></section></div>; }

export function AddMemoryFlow({ memory, milestones, onClose, onSave }: { memory?: Memory; milestones: { id: string; title: string; category: string; achievedDate?: string }[]; onClose: () => void; onSave: (draft: MemoryDraft, id?: string) => void }) {
  const [type, setType] = useState<MemoryType>(memory?.type ?? "photo"); const [title, setTitle] = useState(memory?.title ?? ""); const [date, setDate] = useState(memory?.date ?? defaultDate); const [time, setTime] = useState(memory?.time ?? "12:00"); const [caption, setCaption] = useState(memory?.caption ?? ""); const [note, setNote] = useState(memory?.note ?? ""); const [imagePreview, setImagePreview] = useState(memory?.imagePreview); const [imageAlt, setImageAlt] = useState(memory?.imageAlt ?? ""); const [favorite, setFavorite] = useState(memory?.favorite ?? false); const [privateNote, setPrivateNote] = useState(memory?.privateNote ?? false); const [milestoneId, setMilestoneId] = useState(memory?.milestoneId ?? ""); const [error, setError] = useState<string | null>(null); const fileInput = useRef<HTMLInputElement>(null);
  function handleImage(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) { setError("Choose an image file for the local preview."); return; } if (file.size > 6 * 1024 * 1024) { setError("Choose an image smaller than 6 MB."); return; } setError(null); setImagePreview(URL.createObjectURL(file)); setImageAlt(file.name.replace(/\.[^/.]+$/, "")); }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!title.trim()) { setError("Add a short title for this memory."); return; } const milestone = milestones.find((item) => item.id === milestoneId); onSave({ type, title: title.trim(), date, time: time || undefined, caption: caption.trim() || undefined, note: note.trim() || undefined, imagePreview, imageAlt: imageAlt.trim() || undefined, favorite, privateNote, milestoneId: milestone?.id, milestoneName: milestone?.title, milestoneCategory: milestone?.category, achievedDate: milestone?.achievedDate }, memory?.id); }
  return <div className="memory-sheet-layer"><button className="memory-sheet-layer__overlay" type="button" onClick={onClose} aria-label="Close memory form" /><section className="memory-sheet memory-form-sheet" role="dialog" aria-modal="true" aria-labelledby="memory-form-title"><header><div><p>{memory ? "Edit memory" : "A little moment"}</p><h2 id="memory-form-title">{memory ? "Update your memory" : "Add to Memory Book"}</h2></div><button type="button" onClick={onClose} aria-label="Close memory form"><X size={20} /></button></header><form onSubmit={submit}><div className="memory-form__grid"><label>Memory type<select value={type} onChange={(event) => setType(event.target.value as MemoryType)}>{Object.entries(memoryTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Related milestone <em>Optional</em><select value={milestoneId} onChange={(event) => setMilestoneId(event.target.value)}><option value="">No related milestone</option>{milestones.map((milestone) => <option key={milestone.id} value={milestone.id}>{milestone.title}</option>)}</select></label><label className="memory-form__full">Title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="e.g. First big smile" required /></label><label>Date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} required /></label><label>Time <em>Optional</em><input type="time" value={time} onChange={(event) => setTime(event.target.value)} /></label><label className="memory-form__full">Short caption <em>Optional</em><input value={caption} onChange={(event) => setCaption(event.target.value)} placeholder="A few words to remember it by" /></label><label className="memory-form__full">Longer note <em>Optional</em><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="The details you will want to keep..." /></label></div><MemoryImagePicker imagePreview={imagePreview} imageAlt={imageAlt} inputRef={fileInput} onImage={handleImage} onRemove={() => { setImagePreview(undefined); setImageAlt(""); if (fileInput.current) fileInput.current.value = ""; }} onAltChange={setImageAlt} /><label className="memory-check"><input type="checkbox" checked={favorite} onChange={(event) => setFavorite(event.target.checked)} />Keep this as a favorite</label><label className="memory-check"><input type="checkbox" checked={privateNote} onChange={(event) => setPrivateNote(event.target.checked)} />Private note <em>Placeholder for future sharing controls</em></label>{error ? <p className="memory-form__error" role="alert">{error}</p> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>Cancel</button><button type="submit" className="button button--primary">{memory ? "Save changes" : "Save memory"}</button></footer></form></section></div>;
}

export function MemoryImagePicker({ imagePreview, imageAlt, inputRef, onImage, onRemove, onAltChange }: { imagePreview?: string; imageAlt: string; inputRef: React.RefObject<HTMLInputElement | null>; onImage: (event: React.ChangeEvent<HTMLInputElement>) => void; onRemove: () => void; onAltChange: (value: string) => void }) { return <div className="memory-image-picker"><div><p>Local photo preview <em>Optional, not uploaded</em></p><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={onImage} /></div>{imagePreview ? <div className="memory-image-picker__preview"><img src={imagePreview} alt={imageAlt || "Local memory preview"} /><button type="button" onClick={onRemove} aria-label="Remove selected memory image"><X size={16} aria-hidden="true" />Remove</button><label>Image description <em>Optional alt text</em><input value={imageAlt} onChange={(event) => onAltChange(event.target.value)} /></label></div> : <span><Upload size={18} aria-hidden="true" />PNG, JPG or WebP up to 6 MB</span>}</div>; }

export function DailyJournalCard({ summary, entry, onEdit }: { summary: string; entry?: JournalEntry; onEdit: () => void }) { return <section className="daily-journal-card"><header><div><BookOpen size={19} aria-hidden="true" /><div><p>Today&apos;s journal</p><h2>A soft record of today</h2></div></div><button type="button" onClick={onEdit}>{entry ? "Edit" : "Add note"}</button></header><p>{summary}</p>{entry?.highlight ? <strong><Sparkles size={15} aria-hidden="true" />{entry.highlight}</strong> : null}{entry?.note ? <span>{entry.note}</span> : <small>No personal note yet. Add one whenever it feels right.</small>}</section>; }
export function JournalEntryForm({ entry, summary, onClose, onSave }: { entry?: JournalEntry; summary: string; onClose: () => void; onSave: (draft: JournalDraft, id?: string) => void }) { const [date, setDate] = useState(entry?.date ?? defaultDate); const [highlight, setHighlight] = useState(entry?.highlight ?? ""); const [note, setNote] = useState(entry?.note ?? ""); return <div className="memory-sheet-layer"><button className="memory-sheet-layer__overlay" type="button" onClick={onClose} aria-label="Close journal form" /><section className="memory-sheet memory-form-sheet" role="dialog" aria-modal="true" aria-labelledby="journal-form-title"><header><div><p>Daily journal</p><h2 id="journal-form-title">{entry ? "Update today" : "Save today"}</h2></div><button type="button" onClick={onClose} aria-label="Close journal form"><X size={20} /></button></header><form onSubmit={(event) => { event.preventDefault(); onSave({ date, summary, highlight: highlight.trim() || undefined, note: note.trim() || undefined }, entry?.id); }}><label>Journal date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><div className="journal-summary"><p>Local activity summary</p><span>{summary}</span></div><label>Highlight of the day <em>Optional</em><input value={highlight} onChange={(event) => setHighlight(event.target.value)} placeholder="e.g. A calm afternoon together" /></label><label>Personal note <em>Optional</em><textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="A few words for future you..." /></label><footer><button type="button" className="button button--secondary" onClick={onClose}>Cancel</button><button type="submit" className="button button--primary">Save journal</button></footer></form></section></div>; }
export function JournalHistory({ entries, onEdit, onDelete }: { entries: JournalEntry[]; onEdit: (entry: JournalEntry) => void; onDelete: (entry: JournalEntry) => void }) { return <section className="journal-history"><header><div><p>Journal history</p><h2>Days you&apos;ve kept</h2></div><CalendarDays size={19} aria-hidden="true" /></header>{entries.length ? entries.toSorted((a, b) => b.date.localeCompare(a.date)).map((entry) => <article key={entry.id}><time>{formatMemoryDate(entry.date)}</time><div><strong>{entry.highlight || "A little day together"}</strong><p>{entry.note || entry.summary}</p></div><button type="button" onClick={() => onEdit(entry)} aria-label={`Edit journal entry for ${entry.date}`}><Edit3 size={16} /></button><button type="button" onClick={() => onDelete(entry)} aria-label={`Delete journal entry for ${entry.date}`}><Trash2 size={16} /></button></article>) : <div className="journal-history__empty"><PiluIllustration variant="teddy" alt="" /><span>No journal entries yet. Today&apos;s first page is waiting.</span></div>}</section>; }
export function MonthlyRecapCard({ recap, onComingSoon }: { recap: ReturnType<typeof createMonthlyRecap>; onComingSoon: () => void }) { return <section className="monthly-recap-card"><div className="monthly-recap-card__moon"><PiluIllustration variant="sleeping-baby" alt="" /></div><div><p>Monthly recap</p><h2>{recap.label}</h2><span>Little moments, kept together.</span></div><dl><div><dt>{recap.memoryCount}</dt><dd>memories</dd></div><div><dt>{recap.milestoneCount}</dt><dd>milestones</dd></div><div><dt>{recap.loggedDays}</dt><dd>logged days</dd></div><div><dt>{recap.photoCount}</dt><dd>photos</dd></div></dl>{recap.favoriteMemory ? <div className="monthly-recap-card__favorite"><Heart size={15} fill="currentColor" aria-hidden="true" />Favorite: {recap.favoriteMemory.title}</div> : null}<button type="button" disabled><Sparkles size={16} aria-hidden="true" />Generate AI story</button><small>AI monthly stories will be available later.</small><div className="monthly-recap-card__actions"><button type="button" onClick={onComingSoon}>Share</button><button type="button" onClick={onComingSoon}>Export</button><button type="button" onClick={onComingSoon}>Create album</button></div></section>; }
export function MemoryEmptyState({ filter, onAdd }: { filter: MemoryFilter; onAdd: () => void }) { const favorite = filter === "favorites"; return <section className="memory-empty-state"><PiluIllustration variant={favorite ? "teddy" : "sleeping-baby"} alt="" /><div><p>{favorite ? "No favorites yet" : "A quiet page"}</p><h2>{favorite ? "Keep the moments that matter most close." : "Your first memory is ready to be saved."}</h2><span>{filter === "all" ? "Photos, little notes and milestone memories will gather here." : "Try another filter or add a new little moment."}</span><button type="button" className="button button--primary" onClick={onAdd}><Plus size={16} aria-hidden="true" />Add memory</button></div></section>; }

function ConfirmMemoryDelete({ open, title, onCancel, onConfirm }: { open: boolean; title: string; onCancel: () => void; onConfirm: () => void }) { const cancel = useRef<HTMLButtonElement>(null); useEffect(() => { if (!open) return; cancel.current?.focus(); const escape = (event: KeyboardEvent) => event.key === "Escape" && onCancel(); window.addEventListener("keydown", escape); return () => window.removeEventListener("keydown", escape); }, [open, onCancel]); if (!open) return null; return <div className="dialog-layer"><button className="dialog-layer__overlay" type="button" onClick={onCancel} aria-label="Close memory deletion confirmation" /><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="memory-delete-title"><p>Memory Book</p><h2 id="memory-delete-title">Delete {title}?</h2><span>This only removes it from this local session.</span><div><button ref={cancel} type="button" className="button button--secondary" onClick={onCancel}>Keep memory</button><button type="button" className="button button--danger" onClick={onConfirm}>Delete</button></div></section></div>; }
