"use client";
/* eslint-disable react-hooks/set-state-in-effect -- feature data is hydrated from Supabase after the active baby resolves. */

import { useActivities } from "@/components/activity/activity-provider";
import { usePiluData } from "@/components/data/pilu-data-provider";
import { initialJournalEntries, initialMemories, sortMemories } from "@/lib/memory-data";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import type { JournalDraft, JournalEntry, Memory, MemoryDraft } from "@/types/memory";
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type MemoryContextValue = { memories: Memory[]; journalEntries: JournalEntry[]; saveMemory: (draft: MemoryDraft, id?: string) => void; removeMemory: (id: string) => void; toggleFavorite: (id: string) => void; saveJournal: (draft: JournalDraft, id?: string) => void; removeJournal: (id: string) => void; };
const MemoryContext = createContext<MemoryContextValue | null>(null);
const when = (date: string, time?: string) => new Date(`${date}T${time || "12:00"}:00`).toISOString();

export function MemoryProvider({ children }: { children: ReactNode }) {
  const { configured, activeBaby, userId } = usePiluData(); const [memories, setMemories] = useState<Memory[]>(configured ? [] : initialMemories); const [journalEntries, setJournalEntries] = useState<JournalEntry[]>(configured ? [] : initialJournalEntries); const { addActivity, updateActivity, removeActivity } = useActivities();
  useEffect(() => { if (!configured) { setMemories(initialMemories); setJournalEntries(initialJournalEntries); return; } if (!activeBaby) { setMemories([]); setJournalEntries([]); return; } let cancelled = false; void (async () => { const supabase = createBrowserSupabaseClient(); const [{ data: memoryRows }, { data: journalRows }] = await Promise.all([supabase.from("memories").select().eq("baby_id", activeBaby.id).order("occurred_at", { ascending: false }), supabase.from("journal_entries").select().eq("baby_id", activeBaby.id).order("entry_date", { ascending: false })]); if (cancelled) return; setMemories((memoryRows || []).map((row) => { const date = new Date(row.occurred_at); return { id: row.id, type: row.memory_type as Memory["type"], title: row.title, date: date.toISOString().slice(0, 10), time: date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false }), caption: row.caption || undefined, note: row.notes || undefined, favorite: row.is_favorite, privateNote: false, imagePreview: row.image_path || undefined, source: "memoryBook" }; })); setJournalEntries((journalRows || []).map((row) => ({ id: row.id, date: row.entry_date, summary: row.activity_summary, note: row.parent_note || undefined, highlight: row.highlight || undefined }))); })(); return () => { cancelled = true; }; }, [configured, activeBaby]);
  const saveMemory = (draft: MemoryDraft, id?: string) => { const current = id ? memories.find((memory) => memory.id === id) : undefined; const activity = { kind: "memory" as const, dateKey: "today" as const, time: draft.time || "12:00", title: "Memory", value: draft.title, note: draft.caption || draft.note }; const timelineActivityId = current?.timelineActivityId ? (updateActivity(current.timelineActivityId, activity), current.timelineActivityId) : addActivity(activity); const memory: Memory = { ...draft, id: id ?? `memory-${Date.now()}`, timelineActivityId, source: "memoryBook" }; setMemories((all) => sortMemories(id ? all.map((item) => item.id === id ? memory : item) : [memory, ...all])); if (configured && activeBaby && userId) void (id ? createBrowserSupabaseClient().from("memories").update({ memory_type: draft.type, title: draft.title, caption: draft.caption || null, notes: draft.note || null, occurred_at: when(draft.date, draft.time), image_path: draft.imagePreview || null, is_favorite: draft.favorite }).eq("id", id) : createBrowserSupabaseClient().from("memories").insert({ baby_id: activeBaby.id, created_by: userId, memory_type: draft.type, title: draft.title, caption: draft.caption || null, notes: draft.note || null, occurred_at: when(draft.date, draft.time), image_path: draft.imagePreview || null, is_favorite: draft.favorite })); };
  const removeMemory = (id: string) => { const target = memories.find((memory) => memory.id === id); if (target?.timelineActivityId) removeActivity(target.timelineActivityId); setMemories((all) => all.filter((memory) => memory.id !== id)); if (configured && !id.startsWith("memory-")) void createBrowserSupabaseClient().from("memories").delete().eq("id", id); };
  const toggleFavorite = (id: string) => { const target = memories.find((memory) => memory.id === id); if (!target) return; setMemories((all) => all.map((memory) => memory.id === id ? { ...memory, favorite: !memory.favorite } : memory)); if (configured && !id.startsWith("memory-")) void createBrowserSupabaseClient().from("memories").update({ is_favorite: !target.favorite }).eq("id", id); };
  const saveJournal = (draft: JournalDraft, id?: string) => { const next = { ...draft, id: id ?? `journal-${Date.now()}` }; setJournalEntries((all) => id ? all.map((entry) => entry.id === id ? next : entry) : [next, ...all]); if (configured && activeBaby && userId) void (id ? createBrowserSupabaseClient().from("journal_entries").update({ entry_date: draft.date, activity_summary: draft.summary, parent_note: draft.note || null, highlight: draft.highlight || null }).eq("id", id) : createBrowserSupabaseClient().from("journal_entries").insert({ baby_id: activeBaby.id, created_by: userId, entry_date: draft.date, activity_summary: draft.summary, parent_note: draft.note || null, highlight: draft.highlight || null })); };
  const removeJournal = (id: string) => { setJournalEntries((all) => all.filter((entry) => entry.id !== id)); if (configured && !id.startsWith("journal-")) void createBrowserSupabaseClient().from("journal_entries").delete().eq("id", id); };
  const value = { memories, journalEntries, saveMemory, removeMemory, toggleFavorite, saveJournal, removeJournal }; return <MemoryContext.Provider value={value}>{children}</MemoryContext.Provider>;
}
export function useMemories() { const context = useContext(MemoryContext); if (!context) throw new Error("useMemories must be used inside MemoryProvider"); return context; }
