"use client";

import { useLocale } from "@/components/i18n/locale-provider";
import type { ActivityDraft } from "@/types/activity";
import { X } from "lucide-react";
import { useState, type FormEvent } from "react";

export function BottleFormSheet({ open, onClose, onSave }: { open: boolean; onClose: () => void; onSave: (activity: ActivityDraft) => void }) {
  const { t } = useLocale();
  const dict = t((d) => d.care.feeding.bottleForm);
  const [values, setValues] = useState({ date: "2026-07-10", time: "18:30", prepared: "120", consumed: "120", milkType: "Formula", temperature: "Warm", duration: "15", note: "" });
  const update = (name: keyof typeof values, value: string) => setValues((current) => ({ ...current, [name]: value }));
  const field = (name: keyof typeof values, label: string, type = "text") => <label className="activity-form__field"><span>{label}</span><input type={type} value={values[name]} onChange={(event) => update(name, event.target.value)} /></label>;
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!values.consumed) return; onSave({ kind: "bottle", dateKey: "today", time: values.time, title: "Feeding", value: `${values.consumed} ml`, secondary: `Bottle · ${values.milkType}`, note: values.note || `Prepared ${values.prepared} ml · ${values.temperature} · ${values.duration} min` }); onClose(); }
  return <div className={`activity-form-layer${open ? " activity-form-layer--open" : ""}`} aria-hidden={!open} inert={!open}><button className="bottom-sheet-overlay" type="button" onClick={onClose} aria-label={dict.closeLabel} /><section className="activity-form-sheet" role="dialog" aria-modal="true" aria-label={dict.addTitle}><div className="activity-form-sheet__top"><span aria-hidden="true" /><h2>{dict.addTitle}</h2><button type="button" className="icon-button icon-button--soft" onClick={onClose} aria-label={dict.closeLabel}><X size={20} aria-hidden="true" /></button></div><form className="activity-form" onSubmit={save}><div className="activity-form__grid">{field("date", dict.date, "date")}{field("time", dict.startTime, "time")}{field("prepared", dict.amountPrepared, "number")}{field("consumed", dict.amountConsumed, "number")}<label className="activity-form__field"><span>{dict.milkType}</span><select value={values.milkType} onChange={(event) => update("milkType", event.target.value)}>{["Formula", "Breast milk", "Mixed"].map((option) => <option key={option}>{option}</option>)}</select></label><label className="activity-form__field"><span>{dict.bottleTemperature}</span><select value={values.temperature} onChange={(event) => update("temperature", event.target.value)}>{["Room temperature", "Warm", "Cold", "Custom temperature"].map((option) => <option key={option}>{option}</option>)}</select></label>{field("duration", dict.duration, "number")}<label className="activity-form__field activity-form__field--full"><span>{dict.note} <em>{dict.optional}</em></span><textarea rows={3} value={values.note} onChange={(event) => update("note", event.target.value)} /></label></div><div className="activity-form__actions"><button type="button" className="button button--secondary" onClick={onClose}>{dict.cancel}</button><button type="submit" className="button button--primary">{dict.save}</button></div></form></section></div>;
}
