"use client";
/* eslint-disable react-hooks/set-state-in-effect -- feature data is hydrated from Supabase after the active baby resolves. */

import { useActivities } from "@/components/activity/activity-provider";
import { usePiluData } from "@/components/data/pilu-data-provider";
import { initialAppointments, initialLogs, initialMedicines, initialSchedule, initialTemperatures, initialVaccines, sortAppointments } from "@/lib/care-data";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import type { MedicineLog, MedicineLogStatus, MedicineRecord, MedicineScheduleEntry, TemperatureReading, VaccineRecord } from "@/types/care";
import type { ActivityDraft } from "@/types/activity";
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

type CareContextValue = { vaccines: VaccineRecord[]; appointments: typeof initialAppointments; medicines: MedicineRecord[]; schedule: MedicineScheduleEntry[]; logs: MedicineLog[]; temperatures: TemperatureReading[]; saveVaccine: (record: Omit<VaccineRecord, "id" | "timelineActivityId">, id?: string) => void; removeVaccine: (id: string) => void; markAppointmentCompleted: (appointmentId: string) => void; saveMedicine: (record: Omit<MedicineRecord, "id">, id?: string) => void; removeMedicine: (id: string) => void; setScheduleStatus: (id: string, status: Exclude<MedicineLogStatus, "upcoming">, note?: string) => void; updateMedicineLogNote: (id: string, note?: string) => void; removeMedicineLog: (id: string) => void; recordTemperature: (activity: ActivityDraft) => void; };
const CareContext = createContext<CareContextValue | null>(null);
const vaccineStatus = (status: VaccineRecord["status"]) => status === "upcoming" ? "scheduled" : status === "needsAttention" ? "postponed" : status;
const fromVaccineStatus = (status: "scheduled" | "completed" | "postponed" | "skipped"): VaccineRecord["status"] => status === "scheduled" ? "upcoming" : status === "skipped" ? "needsAttention" : status;

export function CareProvider({ children }: { children: ReactNode }) {
  const { configured, activeBaby, userId } = usePiluData();
  const [vaccines, setVaccines] = useState<VaccineRecord[]>(configured ? [] : initialVaccines); const [appointments] = useState(initialAppointments); const [medicines, setMedicines] = useState<MedicineRecord[]>(configured ? [] : initialMedicines); const [schedule, setSchedule] = useState<MedicineScheduleEntry[]>(configured ? [] : initialSchedule); const [logs, setLogs] = useState<MedicineLog[]>(configured ? [] : initialLogs); const [temperatures, setTemperatures] = useState<TemperatureReading[]>(configured ? [] : initialTemperatures); const { addActivity, updateActivity, removeActivity } = useActivities();
  useEffect(() => { if (!configured) { setVaccines(initialVaccines); setMedicines(initialMedicines); setSchedule(initialSchedule); setLogs(initialLogs); setTemperatures(initialTemperatures); return; } if (!activeBaby) { setVaccines([]); setMedicines([]); setSchedule([]); setLogs([]); setTemperatures([]); return; } let cancelled = false; void (async () => { const supabase = createBrowserSupabaseClient(); const [{ data: vaccineRows }, { data: planRows }, { data: medicineRows }] = await Promise.all([supabase.from("vaccines").select().eq("baby_id", activeBaby.id), supabase.from("medicine_plans").select().eq("baby_id", activeBaby.id), supabase.from("medicine_logs").select().eq("baby_id", activeBaby.id).order("administered_at", { ascending: false })]); if (cancelled) return; const nextMedicines = (planRows || []).map((row) => ({ id: row.id, name: row.medicine_name, type: row.medicine_type as MedicineRecord["type"], doseText: row.dose_text, instructions: row.instructions || undefined, frequency: row.frequency as MedicineRecord["frequency"], times: row.times, startDate: row.start_date, endDate: row.end_date || undefined, doctor: row.doctor || undefined, notes: row.notes || undefined, active: row.active })); setVaccines((vaccineRows || []).map((row) => ({ id: row.id, name: row.vaccine_name, dose: row.dose_label || undefined, plannedDate: row.scheduled_date || "", completedDate: row.administered_date || undefined, clinic: row.healthcare_provider || undefined, notes: row.notes || undefined, status: fromVaccineStatus(row.status), reminder: "none" }))); setMedicines(nextMedicines); setSchedule(nextMedicines.flatMap((medicine) => medicine.active ? medicine.times.map((time, index) => ({ id: `${medicine.id}-${index}`, medicineId: medicine.id, time, status: "upcoming" as const })) : [])); setLogs((medicineRows || []).map((row) => { const date = new Date(row.administered_at); const medicine = nextMedicines.find((plan) => plan.name === row.medicine_name); return { id: row.id, medicineId: medicine?.id || row.medicine_name, date: date.toISOString().slice(0, 10), time: date.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false }), status: "given" as const, doseText: `${row.amount ?? ""}${row.unit || ""}`, note: row.notes || undefined }; })); })(); return () => { cancelled = true; }; }, [configured, activeBaby]);
  function saveVaccine(draft: Omit<VaccineRecord, "id" | "timelineActivityId">, id?: string) { const previous = id ? vaccines.find((record) => record.id === id) : undefined; let timelineActivityId = previous?.timelineActivityId; if (draft.status === "completed") { const activity = { kind: "vaccine" as const, dateKey: "today" as const, time: "12:00", title: "Vaccine completed", value: `${draft.name}${draft.dose ? ` — ${draft.dose}` : ""}`, note: draft.notes }; timelineActivityId = timelineActivityId ? (updateActivity(timelineActivityId, activity), timelineActivityId) : addActivity(activity); } else if (timelineActivityId) { removeActivity(timelineActivityId); timelineActivityId = undefined; } const next = { ...draft, id: id ?? `vaccine-${Date.now()}`, timelineActivityId }; setVaccines((all) => id ? all.map((record) => record.id === id ? next : record) : [...all, next]); if (configured && activeBaby && userId) void (id ? createBrowserSupabaseClient().from("vaccines").update({ vaccine_name: draft.name, dose_label: draft.dose || null, scheduled_date: draft.plannedDate || null, administered_date: draft.completedDate || null, healthcare_provider: draft.clinic || null, notes: draft.notes || null, status: vaccineStatus(draft.status) }).eq("id", id) : createBrowserSupabaseClient().from("vaccines").insert({ baby_id: activeBaby.id, created_by: userId, vaccine_name: draft.name, dose_label: draft.dose || null, scheduled_date: draft.plannedDate || null, administered_date: draft.completedDate || null, healthcare_provider: draft.clinic || null, notes: draft.notes || null, status: vaccineStatus(draft.status) })); }
  function removeVaccine(id: string) { const target = vaccines.find((record) => record.id === id); if (target?.timelineActivityId) removeActivity(target.timelineActivityId); setVaccines((all) => all.filter((record) => record.id !== id)); if (configured && !id.startsWith("vaccine-")) void createBrowserSupabaseClient().from("vaccines").delete().eq("id", id); }
  function markAppointmentCompleted(appointmentId: string) { const appointment = appointments.find((item) => item.id === appointmentId); if (!appointment) return; const record = vaccines.find((item) => item.id === appointment.vaccineId); if (record) saveVaccine({ ...record, status: "completed", completedDate: appointment.date }, record.id); }
  function saveMedicine(draft: Omit<MedicineRecord, "id">, id?: string) { const next = { ...draft, id: id ?? `medicine-${Date.now()}` }; setMedicines((all) => id ? all.map((record) => record.id === id ? next : record) : [...all, next]); setSchedule((all) => id ? all.filter((entry) => entry.medicineId !== id).concat(draft.active ? draft.times.filter(Boolean).map((time, index) => ({ id: `${next.id}-${index}`, medicineId: next.id, time, status: "upcoming" as const })) : []) : [...all, ...draft.times.filter(Boolean).map((time, index) => ({ id: `${next.id}-${index}`, medicineId: next.id, time, status: "upcoming" as const }))]); if (configured && activeBaby && userId) void (id ? createBrowserSupabaseClient().from("medicine_plans").update({ medicine_name: draft.name, medicine_type: draft.type, dose_text: draft.doseText, instructions: draft.instructions || null, frequency: draft.frequency, times: draft.times, start_date: draft.startDate, end_date: draft.endDate || null, doctor: draft.doctor || null, notes: draft.notes || null, active: draft.active }).eq("id", id) : createBrowserSupabaseClient().from("medicine_plans").insert({ baby_id: activeBaby.id, created_by: userId, medicine_name: draft.name, medicine_type: draft.type, dose_text: draft.doseText, instructions: draft.instructions || null, frequency: draft.frequency, times: draft.times, start_date: draft.startDate, end_date: draft.endDate || null, doctor: draft.doctor || null, notes: draft.notes || null, active: draft.active })); }
  function removeMedicine(id: string) { setMedicines((all) => all.filter((record) => record.id !== id)); setSchedule((all) => all.filter((entry) => entry.medicineId !== id)); if (configured && !id.startsWith("medicine-")) void createBrowserSupabaseClient().from("medicine_plans").delete().eq("id", id); }
  function setScheduleStatus(id: string, status: Exclude<MedicineLogStatus, "upcoming">, note?: string) { const entry = schedule.find((item) => item.id === id); const medicine = entry ? medicines.find((item) => item.id === entry.medicineId) : undefined; if (!entry || !medicine) return; const activityId = addActivity({ kind: "medicine", dateKey: "today", time: entry.time, title: medicine.name, value: medicine.name, secondary: `${medicine.doseText} · ${status === "given" ? "Given" : "Skipped"}`, note }); setSchedule((all) => all.map((item) => item.id === id ? { ...item, status, note, timelineActivityId: activityId } : item)); const log = { id: `medicine-log-${Date.now()}`, medicineId: medicine.id, date: new Date().toISOString().slice(0, 10), time: entry.time, status, doseText: medicine.doseText, note, timelineActivityId: activityId }; setLogs((all) => [log, ...all]); if (configured && activeBaby && userId && status === "given") { const amount = Number.parseFloat(medicine.doseText); const unit = medicine.doseText.replace(/[\d.\s]/g, "") || null; void createBrowserSupabaseClient().from("medicine_logs").insert({ baby_id: activeBaby.id, created_by: userId, medicine_name: medicine.name, amount: Number.isNaN(amount) ? null : amount, unit, administered_at: new Date(`${log.date}T${log.time}:00`).toISOString(), notes: note || null }); } }
  function updateMedicineLogNote(id: string, note?: string) { setLogs((all) => all.map((log) => log.id === id ? { ...log, note } : log)); if (configured && !id.startsWith("medicine-log-")) void createBrowserSupabaseClient().from("medicine_logs").update({ notes: note || null }).eq("id", id); }
  function removeMedicineLog(id: string) { const target = logs.find((log) => log.id === id); if (target?.timelineActivityId) removeActivity(target.timelineActivityId); setLogs((all) => all.filter((log) => log.id !== id)); if (configured && !id.startsWith("medicine-log-")) void createBrowserSupabaseClient().from("medicine_logs").delete().eq("id", id); }
  function recordTemperature(activity: ActivityDraft) { const timelineActivityId = addActivity(activity); setTemperatures((all) => [{ id: `temperature-${Date.now()}`, time: activity.time, value: activity.value.replace(/[^0-9.]/g, ""), method: activity.secondary, note: activity.note, timelineActivityId }, ...all]); }
  return <CareContext.Provider value={{ vaccines, appointments: sortAppointments(appointments), medicines, schedule, logs, temperatures, saveVaccine, removeVaccine, markAppointmentCompleted, saveMedicine, removeMedicine, setScheduleStatus, updateMedicineLogNote, removeMedicineLog, recordTemperature }}>{children}</CareContext.Provider>;
}
export function useCare() { const context = useContext(CareContext); if (!context) throw new Error("useCare must be used inside CareProvider"); return context; }
