-- Baseline foundation schema — reconstructed, not original.
--
-- Context: the live pilu-ai.app Supabase project (ref kcgtcitpxzmkeddaxdku)
-- has 17 applied migrations. Only the 12 most recent (Sleep Sounds onward,
-- 2026-07-31) were ever committed as files in this repo. The 5 earliest —
-- initial_pilu_foundation, add_timeline_events, add_feature_data_details,
-- harden_function_permissions, add_emergency_contacts (all 2026-07-30) —
-- were applied directly to the live project and never saved. This file
-- closes that gap.
--
-- It was generated by introspecting the LIVE schema via the Supabase MCP
-- SQL channel (pg_catalog/information_schema/pg_policies), not written
-- from memory, and captures every table/enum/function/policy/index/trigger
-- that isn't already accounted for by the 12 existing migration files in
-- this directory. Applying this file plus the existing 12, in order,
-- against an empty Supabase project reproduces the current live schema.
--
-- This file has NOT been applied to the live project (it's already live —
-- applying it there would fail on "already exists"). It exists so this
-- repo can stand up a second environment or recover from scratch. See
-- DEPLOYMENT.md §3 and RELEASE_CHECKLIST.md §3 for the full context.
--
-- Sequencing note: four columns that exist on the live tables today are
-- deliberately NOT created here, because the 12 existing migration files
-- add them later in sequence and would fail on "column already exists"
-- otherwise: profiles.subscription_tier (+ its CHECK) and
-- profiles.analytics_consent, family_members.last_seen_at, and
-- babies.mother_name/father_name. Every CREATE TABLE/TYPE/INDEX/POLICY
-- name in this file was cross-checked against all 12 existing migration
-- files for collisions. This file was not test-applied against a live or
-- local Postgres instance — this sandbox has no Postgres and no network
-- path to Supabase's API — so review it before relying on it in a real
-- disaster-recovery scenario.

create extension if not exists pgcrypto with schema extensions;

-- ── Enum types ────────────────────────────────────────────────────────────

create type public.family_role as enum ('owner', 'parent', 'caregiver');
create type public.family_member_status as enum ('invited', 'active', 'removed');
create type public.feeding_type as enum ('breastfeeding', 'bottle', 'formula', 'pumped_milk', 'solid_food', 'water', 'custom');
create type public.sleep_type as enum ('nap', 'night_sleep', 'custom');
create type public.vaccine_status as enum ('scheduled', 'completed', 'postponed', 'skipped');
create type public.ai_message_role as enum ('user', 'assistant', 'system');
create type public.emergency_contact_type as enum ('general_emergency', 'pediatrician', 'clinic', 'trusted_caregiver', 'poison_information');

-- ── Shared trigger function ─────────────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $function$ begin new.updated_at = now(); return new; end; $function$;

-- ── Tables ───────────────────────────────────────────────────────────────

-- NOTE: subscription_tier (+ its CHECK) and analytics_consent are added
-- later by 20260731080845_add_sleep_sounds.sql and
-- 20260731150000_add_analytics_consent.sql respectively — omitted here so
-- those ALTER TABLE statements have something to add rather than
-- colliding with a column that already exists.
create table public.profiles (
  id uuid not null,
  display_name text,
  first_name text,
  last_name text,
  avatar_url text,
  preferred_language text not null default 'en'::text,
  timezone text not null default 'UTC'::text,
  onboarding_completed boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade,
  constraint profiles_preferred_language_check check (char_length(preferred_language) >= 2 and char_length(preferred_language) <= 16)
);

create table public.families (
  id uuid not null default gen_random_uuid(),
  name text not null,
  owner_id uuid not null,
  invite_code text not null default substr(replace((gen_random_uuid())::text, '-', ''), 1, 16),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint families_pkey primary key (id),
  constraint families_owner_id_fkey foreign key (owner_id) references public.profiles(id) on delete restrict,
  constraint families_invite_code_key unique (invite_code),
  constraint families_invite_code_check check (char_length(invite_code) >= 12),
  constraint families_name_check check (char_length(trim(name)) >= 1 and char_length(trim(name)) <= 120)
);

-- NOTE: last_seen_at is added later by
-- 20260731090426_add_family_collaboration.sql — omitted here for the same
-- reason as profiles.subscription_tier above.
create table public.family_members (
  id uuid not null default gen_random_uuid(),
  family_id uuid not null,
  user_id uuid not null,
  role public.family_role not null default 'parent'::public.family_role,
  status public.family_member_status not null default 'invited'::public.family_member_status,
  joined_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint family_members_pkey primary key (id),
  constraint family_members_family_id_fkey foreign key (family_id) references public.families(id) on delete cascade,
  constraint family_members_user_id_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint family_members_family_id_user_id_key unique (family_id, user_id)
);

-- NOTE: mother_name and father_name are added later by
-- 20260731140313_add_baby_parent_names.sql — omitted here for the same
-- reason as profiles.subscription_tier above.
create table public.babies (
  id uuid not null default gen_random_uuid(),
  family_id uuid not null,
  first_name text not null,
  last_name text,
  nickname text,
  date_of_birth date,
  due_date date,
  biological_sex text,
  birth_weight_grams numeric(8,2),
  birth_length_cm numeric(6,2),
  avatar_url text,
  notes text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint babies_pkey primary key (id),
  constraint babies_family_id_fkey foreign key (family_id) references public.families(id) on delete cascade,
  constraint babies_first_name_check check (char_length(trim(first_name)) >= 1 and char_length(trim(first_name)) <= 80),
  constraint babies_biological_sex_check check (biological_sex = any (array['female'::text, 'male'::text, 'intersex'::text, 'not_specified'::text])),
  constraint babies_birth_weight_grams_check check (birth_weight_grams is null or birth_weight_grams >= 0),
  constraint babies_birth_length_cm_check check (birth_length_cm is null or birth_length_cm >= 0),
  constraint babies_check check (date_of_birth is null or due_date is null or due_date <= date_of_birth)
);

create table public.feeding_logs (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  feeding_type public.feeding_type not null,
  started_at timestamp with time zone not null,
  ended_at timestamp with time zone,
  duration_minutes integer,
  breast_side text,
  amount_ml numeric(8,2),
  food_name text,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint feeding_logs_pkey primary key (id),
  constraint feeding_logs_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint feeding_logs_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint feeding_logs_breast_side_check check (breast_side is null or breast_side = any (array['left'::text, 'right'::text, 'both'::text])),
  constraint feeding_logs_amount_ml_check check (amount_ml is null or amount_ml >= 0),
  constraint feeding_logs_duration_minutes_check check (duration_minutes is null or duration_minutes >= 0),
  constraint feeding_logs_check check (ended_at is null or ended_at >= started_at)
);

create table public.sleep_logs (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  started_at timestamp with time zone not null,
  ended_at timestamp with time zone,
  duration_minutes integer,
  sleep_type public.sleep_type not null default 'nap'::public.sleep_type,
  sleep_location text,
  quality text,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint sleep_logs_pkey primary key (id),
  constraint sleep_logs_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint sleep_logs_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint sleep_logs_quality_check check (quality is null or quality = any (array['restless'::text, 'fair'::text, 'good'::text, 'unknown'::text])),
  constraint sleep_logs_duration_minutes_check check (duration_minutes is null or duration_minutes >= 0),
  constraint sleep_logs_check check (ended_at is null or ended_at >= started_at)
);

create table public.diaper_logs (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  logged_at timestamp with time zone not null default now(),
  diaper_type text not null,
  stool_color text,
  stool_consistency text,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint diaper_logs_pkey primary key (id),
  constraint diaper_logs_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint diaper_logs_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint diaper_logs_diaper_type_check check (diaper_type = any (array['wet'::text, 'dirty'::text, 'mixed'::text, 'dry'::text, 'other'::text]))
);

create table public.growth_logs (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  measured_at timestamp with time zone not null,
  weight_grams numeric(10,2),
  height_cm numeric(7,2),
  head_circumference_cm numeric(7,2),
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint growth_logs_pkey primary key (id),
  constraint growth_logs_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint growth_logs_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint growth_logs_weight_grams_check check (weight_grams is null or weight_grams >= 0),
  constraint growth_logs_height_cm_check check (height_cm is null or height_cm >= 0),
  constraint growth_logs_head_circumference_cm_check check (head_circumference_cm is null or head_circumference_cm >= 0)
);

create table public.milestones (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  title text not null,
  category text not null,
  achieved_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  description text not null default ''::text,
  status text not null default 'upcoming'::text,
  typical_age text,
  constraint milestones_pkey primary key (id),
  constraint milestones_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint milestones_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint milestones_title_check check (char_length(trim(title)) >= 1 and char_length(trim(title)) <= 160),
  constraint milestones_status_check check (status = any (array['upcoming'::text, 'inProgress'::text, 'achieved'::text, 'notApplicable'::text]))
);

create table public.vaccines (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  vaccine_name text not null,
  scheduled_date date,
  administered_date date,
  status public.vaccine_status not null default 'scheduled'::public.vaccine_status,
  dose_label text,
  healthcare_provider text,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint vaccines_pkey primary key (id),
  constraint vaccines_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint vaccines_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint vaccines_vaccine_name_check check (char_length(trim(vaccine_name)) >= 1 and char_length(trim(vaccine_name)) <= 160),
  constraint vaccines_check check (administered_date is null or scheduled_date is null or administered_date >= (scheduled_date - 3650))
);

create table public.medicine_logs (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  medicine_name text not null,
  amount numeric(9,3),
  unit text,
  administered_at timestamp with time zone not null,
  prescribed_by text,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint medicine_logs_pkey primary key (id),
  constraint medicine_logs_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint medicine_logs_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint medicine_logs_medicine_name_check check (char_length(trim(medicine_name)) >= 1 and char_length(trim(medicine_name)) <= 160),
  constraint medicine_logs_amount_check check (amount is null or amount >= 0)
);

create table public.medicine_plans (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  medicine_name text not null,
  medicine_type text not null,
  dose_text text not null,
  instructions text,
  frequency text not null,
  times text[] not null default '{}'::text[],
  start_date date not null,
  end_date date,
  doctor text,
  notes text,
  active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint medicine_plans_pkey primary key (id),
  constraint medicine_plans_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint medicine_plans_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint medicine_plans_medicine_name_check check (char_length(trim(medicine_name)) >= 1 and char_length(trim(medicine_name)) <= 160),
  constraint medicine_plans_medicine_type_check check (medicine_type = any (array['medicine'::text, 'vitamin'::text, 'supplement'::text, 'other'::text]))
);

create table public.memories (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  memory_type text not null,
  title text not null,
  caption text,
  notes text,
  occurred_at timestamp with time zone not null,
  image_path text,
  related_milestone_id uuid,
  is_favorite boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint memories_pkey primary key (id),
  constraint memories_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint memories_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint memories_related_milestone_id_fkey foreign key (related_milestone_id) references public.milestones(id) on delete set null,
  constraint memories_title_check check (char_length(trim(title)) >= 1 and char_length(trim(title)) <= 160)
);

create table public.journal_entries (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  entry_date date not null,
  activity_summary text not null,
  parent_note text,
  highlight text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint journal_entries_pkey primary key (id),
  constraint journal_entries_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint journal_entries_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint journal_entries_baby_id_entry_date_key unique (baby_id, entry_date)
);

create table public.article_bookmarks (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  article_slug text not null,
  created_at timestamp with time zone not null default now(),
  constraint article_bookmarks_pkey primary key (id),
  constraint article_bookmarks_user_id_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint article_bookmarks_user_id_article_slug_key unique (user_id, article_slug),
  constraint article_bookmarks_article_slug_check check (char_length(trim(article_slug)) >= 1 and char_length(trim(article_slug)) <= 200)
);

create table public.article_feedback (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  article_slug text not null,
  was_helpful boolean not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint article_feedback_pkey primary key (id),
  constraint article_feedback_user_id_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint article_feedback_user_id_article_slug_key unique (user_id, article_slug),
  constraint article_feedback_article_slug_check check (char_length(trim(article_slug)) >= 1 and char_length(trim(article_slug)) <= 200)
);

create table public.ai_conversations (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  baby_id uuid,
  title text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint ai_conversations_pkey primary key (id),
  constraint ai_conversations_user_id_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint ai_conversations_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete set null
);

create table public.ai_messages (
  id uuid not null default gen_random_uuid(),
  conversation_id uuid not null,
  role public.ai_message_role not null,
  content text not null,
  created_at timestamp with time zone not null default now(),
  constraint ai_messages_pkey primary key (id),
  constraint ai_messages_conversation_id_fkey foreign key (conversation_id) references public.ai_conversations(id) on delete cascade,
  constraint ai_messages_content_check check (char_length(content) > 0)
);

create table public.timeline_events (
  id uuid not null default gen_random_uuid(),
  baby_id uuid not null,
  created_by uuid,
  event_kind text not null,
  occurred_at timestamp with time zone not null,
  title text not null,
  value text not null default ''::text,
  secondary text,
  note text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint timeline_events_pkey primary key (id),
  constraint timeline_events_baby_id_fkey foreign key (baby_id) references public.babies(id) on delete cascade,
  constraint timeline_events_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint timeline_events_event_kind_check check (event_kind = any (array['feeding'::text, 'breastfeeding'::text, 'bottle'::text, 'sleep'::text, 'diaper'::text, 'temperature'::text, 'medicine'::text, 'vaccine'::text, 'weight'::text, 'memory'::text])),
  constraint timeline_events_title_check check (char_length(trim(title)) >= 1 and char_length(trim(title)) <= 160)
);

create table public.emergency_contacts (
  id uuid not null default gen_random_uuid(),
  family_id uuid not null,
  created_by uuid,
  contact_type public.emergency_contact_type not null,
  label text not null,
  name text,
  phone_number text,
  country_code text,
  is_primary boolean not null default false,
  notes text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint emergency_contacts_pkey primary key (id),
  constraint emergency_contacts_family_id_fkey foreign key (family_id) references public.families(id) on delete cascade,
  constraint emergency_contacts_created_by_fkey foreign key (created_by) references public.profiles(id) on delete set null,
  constraint emergency_contacts_family_id_contact_type_key unique (family_id, contact_type),
  constraint emergency_contacts_label_check check (char_length(trim(label)) >= 1 and char_length(trim(label)) <= 100),
  constraint emergency_contacts_country_code_check check (country_code is null or (char_length(country_code) >= 2 and char_length(country_code) <= 3))
);

-- ── Indexes ──────────────────────────────────────────────────────────────

create index babies_family_active_idx on public.babies using btree (family_id, is_active);
create index family_members_family_user_active_idx on public.family_members using btree (family_id, user_id) where (status = 'active'::public.family_member_status);
create index feeding_logs_baby_started_idx on public.feeding_logs using btree (baby_id, started_at desc);
create index sleep_logs_baby_started_idx on public.sleep_logs using btree (baby_id, started_at desc);
create index diaper_logs_baby_logged_idx on public.diaper_logs using btree (baby_id, logged_at desc);
create index growth_logs_baby_measured_idx on public.growth_logs using btree (baby_id, measured_at desc);
create index milestones_baby_achieved_idx on public.milestones using btree (baby_id, achieved_at desc);
create index vaccines_baby_scheduled_idx on public.vaccines using btree (baby_id, scheduled_date);
create index medicine_logs_baby_administered_idx on public.medicine_logs using btree (baby_id, administered_at desc);
create index medicine_plans_baby_active_idx on public.medicine_plans using btree (baby_id, active);
create index memories_baby_occurred_idx on public.memories using btree (baby_id, occurred_at desc);
create index journal_entries_baby_date_idx on public.journal_entries using btree (baby_id, entry_date desc);
create index ai_conversations_user_updated_idx on public.ai_conversations using btree (user_id, updated_at desc);
create index ai_messages_conversation_created_idx on public.ai_messages using btree (conversation_id, created_at);
create index timeline_events_baby_occurred_idx on public.timeline_events using btree (baby_id, occurred_at desc);
create index emergency_contacts_family_idx on public.emergency_contacts using btree (family_id);

-- ── Access-check functions (SECURITY DEFINER, RPC layer) ───────────────
-- Each does its own authorization check internally; EXECUTE is revoked
-- from anon/public below, matching the pattern the later migrations in
-- this directory use and harden further.

create or replace function public.is_active_family_member(target_family_id uuid)
returns boolean
language sql
stable security definer
set search_path to 'public'
as $function$
  select exists (select 1 from public.family_members fm where fm.family_id = target_family_id and fm.user_id = (select auth.uid()) and fm.status = 'active');
$function$;

create or replace function public.is_family_owner(target_family_id uuid)
returns boolean
language sql
stable security definer
set search_path to 'public'
as $function$
  select exists (select 1 from public.families f where f.id = target_family_id and f.owner_id = (select auth.uid()));
$function$;

create or replace function public.can_access_baby(target_baby_id uuid)
returns boolean
language sql
stable security definer
set search_path to 'public'
as $function$
  select exists (select 1 from public.babies b where b.id = target_baby_id and public.is_active_family_member(b.family_id));
$function$;

create or replace function public.owns_ai_conversation(target_conversation_id uuid)
returns boolean
language sql
stable security definer
set search_path to 'public'
as $function$
  select exists (select 1 from public.ai_conversations c where c.id = target_conversation_id and c.user_id = (select auth.uid()));
$function$;

create or replace function public.create_family(family_name text)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $function$
declare new_family_id uuid;
begin
  if (select auth.uid()) is null then raise exception 'Authentication is required'; end if;
  if nullif(trim(family_name), '') is null then raise exception 'Family name is required'; end if;
  insert into public.families (name, owner_id) values (trim(family_name), (select auth.uid())) returning id into new_family_id;
  insert into public.family_members (family_id, user_id, role, status, joined_at) values (new_family_id, (select auth.uid()), 'owner', 'active', now());
  return new_family_id;
end; $function$;

revoke execute on function public.is_active_family_member(uuid) from public;
revoke execute on function public.is_active_family_member(uuid) from anon;
grant execute on function public.is_active_family_member(uuid) to authenticated;

revoke execute on function public.is_family_owner(uuid) from public;
revoke execute on function public.is_family_owner(uuid) from anon;
grant execute on function public.is_family_owner(uuid) to authenticated;

revoke execute on function public.can_access_baby(uuid) from public;
revoke execute on function public.can_access_baby(uuid) from anon;
grant execute on function public.can_access_baby(uuid) to authenticated;

revoke execute on function public.owns_ai_conversation(uuid) from public;
revoke execute on function public.owns_ai_conversation(uuid) from anon;
grant execute on function public.owns_ai_conversation(uuid) to authenticated;

revoke execute on function public.create_family(text) from public;
revoke execute on function public.create_family(text) from anon;
grant execute on function public.create_family(text) to authenticated;

-- ── New-user provisioning (auth.users -> public.profiles) ──────────────

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$ begin
  insert into public.profiles (id, display_name, first_name, avatar_url)
  values (new.id, nullif(new.raw_user_meta_data ->> 'full_name', ''), nullif(coalesce(new.raw_user_meta_data ->> 'first_name', split_part(coalesce(new.raw_user_meta_data ->> 'full_name', ''), ' ', 1)), ''), nullif(new.raw_user_meta_data ->> 'avatar_url', ''))
  on conflict (id) do nothing;
  return new;
end; $function$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ── Row Level Security ───────────────────────────────────────────────────

alter table public.profiles enable row level security;
alter table public.families enable row level security;
alter table public.family_members enable row level security;
alter table public.babies enable row level security;
alter table public.feeding_logs enable row level security;
alter table public.sleep_logs enable row level security;
alter table public.diaper_logs enable row level security;
alter table public.growth_logs enable row level security;
alter table public.milestones enable row level security;
alter table public.vaccines enable row level security;
alter table public.medicine_logs enable row level security;
alter table public.medicine_plans enable row level security;
alter table public.memories enable row level security;
alter table public.journal_entries enable row level security;
alter table public.article_bookmarks enable row level security;
alter table public.article_feedback enable row level security;
alter table public.ai_conversations enable row level security;
alter table public.ai_messages enable row level security;
alter table public.timeline_events enable row level security;
alter table public.emergency_contacts enable row level security;

-- profiles: each user owns exactly their own row
create policy profiles_select_own on public.profiles for select to authenticated using ((select auth.uid()) = id);
create policy profiles_insert_own on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy profiles_update_own on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

-- families
create policy families_select_members on public.families for select to authenticated using (public.is_active_family_member(id));
create policy families_update_owner on public.families for update to authenticated using (public.is_family_owner(id)) with check (owner_id = (select auth.uid()));
create policy families_delete_owner on public.families for delete to authenticated using (public.is_family_owner(id));

-- family_members
create policy family_members_select_members on public.family_members for select to authenticated using (public.is_active_family_member(family_id));
create policy family_members_insert_owner on public.family_members for insert to authenticated with check (public.is_family_owner(family_id));
create policy family_members_update_owner on public.family_members for update to authenticated using (public.is_family_owner(family_id)) with check (public.is_family_owner(family_id));
create policy family_members_delete_owner on public.family_members for delete to authenticated using (public.is_family_owner(family_id));

-- babies
create policy babies_select_members on public.babies for select to authenticated using (public.is_active_family_member(family_id));
create policy babies_insert_members on public.babies for insert to authenticated with check (public.is_active_family_member(family_id));
create policy babies_update_members on public.babies for update to authenticated using (public.is_active_family_member(family_id)) with check (public.is_active_family_member(family_id));
create policy babies_delete_members on public.babies for delete to authenticated using (public.is_active_family_member(family_id));

-- feeding_logs / sleep_logs / diaper_logs / growth_logs / milestones /
-- vaccines / medicine_logs / medicine_plans / memories / journal_entries /
-- timeline_events all share the same shape: any active family member can
-- read, the original creator can edit/delete, any active member can insert
-- (as themselves).

create policy feeding_select_members on public.feeding_logs for select to authenticated using (public.can_access_baby(baby_id));
create policy feeding_insert_members on public.feeding_logs for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy feeding_update_creator on public.feeding_logs for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy feeding_delete_creator on public.feeding_logs for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy sleep_select_members on public.sleep_logs for select to authenticated using (public.can_access_baby(baby_id));
create policy sleep_insert_members on public.sleep_logs for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy sleep_update_creator on public.sleep_logs for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy sleep_delete_creator on public.sleep_logs for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy diaper_select_members on public.diaper_logs for select to authenticated using (public.can_access_baby(baby_id));
create policy diaper_insert_members on public.diaper_logs for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy diaper_update_creator on public.diaper_logs for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy diaper_delete_creator on public.diaper_logs for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy growth_select_members on public.growth_logs for select to authenticated using (public.can_access_baby(baby_id));
create policy growth_insert_members on public.growth_logs for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy growth_update_creator on public.growth_logs for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy growth_delete_creator on public.growth_logs for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy milestones_select_members on public.milestones for select to authenticated using (public.can_access_baby(baby_id));
create policy milestones_insert_members on public.milestones for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy milestones_update_creator on public.milestones for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy milestones_delete_creator on public.milestones for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy vaccines_select_members on public.vaccines for select to authenticated using (public.can_access_baby(baby_id));
create policy vaccines_insert_members on public.vaccines for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy vaccines_update_creator on public.vaccines for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy vaccines_delete_creator on public.vaccines for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy medicine_select_members on public.medicine_logs for select to authenticated using (public.can_access_baby(baby_id));
create policy medicine_insert_members on public.medicine_logs for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy medicine_update_creator on public.medicine_logs for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy medicine_delete_creator on public.medicine_logs for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy medicine_plans_select_members on public.medicine_plans for select to authenticated using (public.can_access_baby(baby_id));
create policy medicine_plans_insert_members on public.medicine_plans for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy medicine_plans_update_creator on public.medicine_plans for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy medicine_plans_delete_creator on public.medicine_plans for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy memories_select_members on public.memories for select to authenticated using (public.can_access_baby(baby_id));
create policy memories_insert_members on public.memories for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy memories_update_creator on public.memories for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy memories_delete_creator on public.memories for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy journals_select_members on public.journal_entries for select to authenticated using (public.can_access_baby(baby_id));
create policy journals_insert_members on public.journal_entries for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy journals_update_creator on public.journal_entries for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy journals_delete_creator on public.journal_entries for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

create policy timeline_events_select_members on public.timeline_events for select to authenticated using (public.can_access_baby(baby_id));
create policy timeline_events_insert_members on public.timeline_events for insert to authenticated with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy timeline_events_update_creator on public.timeline_events for update to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid())) with check (public.can_access_baby(baby_id) and created_by = (select auth.uid()));
create policy timeline_events_delete_creator on public.timeline_events for delete to authenticated using (public.can_access_baby(baby_id) and created_by = (select auth.uid()));

-- article_bookmarks / article_feedback: purely per-user, no family scope
create policy bookmarks_own on public.article_bookmarks for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy feedback_own on public.article_feedback for all to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

-- ai_conversations / ai_messages: Ask Pilu, scoped to the owning user
create policy conversations_own on public.ai_conversations for select to authenticated using (user_id = (select auth.uid()) and (baby_id is null or public.can_access_baby(baby_id)));
create policy conversations_insert_own on public.ai_conversations for insert to authenticated with check (user_id = (select auth.uid()) and (baby_id is null or public.can_access_baby(baby_id)));
create policy conversations_update_own on public.ai_conversations for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()) and (baby_id is null or public.can_access_baby(baby_id)));
create policy conversations_delete_own on public.ai_conversations for delete to authenticated using (user_id = (select auth.uid()));

create policy messages_select_owner on public.ai_messages for select to authenticated using (public.owns_ai_conversation(conversation_id));
create policy messages_insert_owner on public.ai_messages for insert to authenticated with check (public.owns_ai_conversation(conversation_id));
create policy messages_update_owner on public.ai_messages for update to authenticated using (public.owns_ai_conversation(conversation_id)) with check (public.owns_ai_conversation(conversation_id));
create policy messages_delete_owner on public.ai_messages for delete to authenticated using (public.owns_ai_conversation(conversation_id));

-- emergency_contacts: any active member reads; only the family owner
-- manages entries (First Aid contact list is sensitive/shared config)
create policy emergency_contacts_select_members on public.emergency_contacts for select to authenticated using (public.is_active_family_member(family_id));
create policy emergency_contacts_insert_owner on public.emergency_contacts for insert to authenticated with check (public.is_family_owner(family_id) and created_by = (select auth.uid()));
create policy emergency_contacts_update_owner on public.emergency_contacts for update to authenticated using (public.is_family_owner(family_id)) with check (public.is_family_owner(family_id));
create policy emergency_contacts_delete_owner on public.emergency_contacts for delete to authenticated using (public.is_family_owner(family_id));

-- ── updated_at triggers ──────────────────────────────────────────────────

create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger families_updated_at before update on public.families for each row execute function public.set_updated_at();
create trigger babies_updated_at before update on public.babies for each row execute function public.set_updated_at();
create trigger feeding_logs_updated_at before update on public.feeding_logs for each row execute function public.set_updated_at();
create trigger sleep_logs_updated_at before update on public.sleep_logs for each row execute function public.set_updated_at();
create trigger diaper_logs_updated_at before update on public.diaper_logs for each row execute function public.set_updated_at();
create trigger growth_logs_updated_at before update on public.growth_logs for each row execute function public.set_updated_at();
create trigger milestones_updated_at before update on public.milestones for each row execute function public.set_updated_at();
create trigger vaccines_updated_at before update on public.vaccines for each row execute function public.set_updated_at();
create trigger medicine_logs_updated_at before update on public.medicine_logs for each row execute function public.set_updated_at();
create trigger medicine_plans_updated_at before update on public.medicine_plans for each row execute function public.set_updated_at();
create trigger memories_updated_at before update on public.memories for each row execute function public.set_updated_at();
create trigger journal_entries_updated_at before update on public.journal_entries for each row execute function public.set_updated_at();
create trigger article_feedback_updated_at before update on public.article_feedback for each row execute function public.set_updated_at();
create trigger ai_conversations_updated_at before update on public.ai_conversations for each row execute function public.set_updated_at();
create trigger timeline_events_updated_at before update on public.timeline_events for each row execute function public.set_updated_at();
create trigger emergency_contacts_updated_at before update on public.emergency_contacts for each row execute function public.set_updated_at();
