"use client";

import { useBabyProfile } from "@/components/baby/baby-profile-provider";
import { useDevelopment } from "@/components/development/development-provider";
import { formatGrowthDate, formatMeasurementValue, metricLabel, metricUnit, metricValue, sortMeasurements } from "@/lib/development-data";
import type { GrowthMeasurement, GrowthMetric } from "@/types/development";
import { CalendarDays, Pencil, Plus, Scale, Trash2 } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { GrowthChart } from "./growth-chart";

const metrics: GrowthMetric[] = ["weight", "length", "headCircumference"];
const metricShortLabels: Record<GrowthMetric, string> = { weight: "Weight", length: "Length", headCircumference: "Head" };

export function GrowthDashboard() {
  const { measurements, saveMeasurement, removeMeasurement } = useDevelopment();
  const { profile } = useBabyProfile();
  const [metric, setMetric] = useState<GrowthMetric>("weight");
  const [editing, setEditing] = useState<GrowthMeasurement | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const ordered = useMemo(() => sortMeasurements(measurements), [measurements]);
  const latest = ordered.at(-1);
  const previous = ordered.at(-2);
  const currentValue = latest ? metricValue(latest, metric) : 0;
  const change = latest && previous ? currentValue - metricValue(previous, metric) : 0;
  function openAdd() { setEditing(null); setFormOpen(true); }
  function save(draft: Omit<GrowthMeasurement, "id" | "timelineActivityId">, keepOpen: boolean) { saveMeasurement(draft, editing?.id); setToast(editing ? "Measurement updated" : "Measurement added to Growth and Timeline"); if (keepOpen) setEditing(null); else setFormOpen(false); window.setTimeout(() => setToast(null), 3200); }
  return <div className="growth-page"><header className="tracker-page__header"><p>Follow {profile.preferredName}&apos;s growth over time</p><h1>Growth</h1></header><GrowthSummaryCard measurement={latest} onAdd={openAdd} /><section className="growth-metric-tabs" aria-label="Growth metrics">{metrics.map((item) => <button key={item} className={metric === item ? "growth-metric-tabs__button growth-metric-tabs__button--active" : "growth-metric-tabs__button"} type="button" onClick={() => setMetric(item)}>{metricShortLabels[item]}</button>)}</section><section className="growth-current-metric"><span>{metricLabel(metric)}</span><strong>{formatMeasurementValue(currentValue, metric)}</strong><p>{change > 0 ? `+${change.toFixed(metric === "weight" ? 2 : 1)} ${metricUnit(metric)} since the last measurement` : "First saved measurement"}</p></section><GrowthChart metric={metric} measurements={ordered} /><PercentilePlaceholderCard /><GrowthHistoryList measurements={[...ordered].reverse()} onEdit={(measurement) => { setEditing(measurement); setFormOpen(true); }} onDelete={(id) => { removeMeasurement(id); setToast("Measurement removed"); window.setTimeout(() => setToast(null), 3200); }} />{formOpen ? <AddMeasurementForm measurement={editing} onClose={() => setFormOpen(false)} onSave={save} /> : null}{toast ? <div className="pilu-toast" role="status">{toast}</div> : null}</div>;
}

export function GrowthSummaryCard({ measurement, onAdd }: { measurement?: GrowthMeasurement; onAdd: () => void }) { const { profile } = useBabyProfile(); return <section className="growth-summary-card"><div><p>Current growth</p><h2>{profile.preferredName}&apos;s latest check-in</h2></div><button type="button" className="button button--primary" onClick={onAdd}><Plus size={17} aria-hidden="true" />Add measurement</button><div className="growth-summary-card__metrics"><span><strong>{measurement?.weightKg.toFixed(2) ?? "5.10"} kg</strong>Weight</span><span><strong>{measurement?.lengthCm ?? 58} cm</strong>Length</span><span><strong>{measurement?.headCircumferenceCm ?? 38} cm</strong>Head circumference</span></div><small><CalendarDays size={14} aria-hidden="true" />Updated {measurement ? formatGrowthDate(measurement.date) : "today"}</small></section>; }
export function PercentilePlaceholderCard() { return <section className="percentile-placeholder-card"><Scale size={21} aria-hidden="true" /><div><h2>WHO growth percentiles</h2><p>WHO growth percentiles will be added after validated reference data is integrated.</p></div></section>; }
export function GrowthHistoryList({ measurements, onEdit, onDelete }: { measurements: GrowthMeasurement[]; onEdit: (measurement: GrowthMeasurement) => void; onDelete: (id: string) => void }) { return <section className="growth-history"><header><div><p>Growth history</p><h2>Every measurement</h2></div></header><div>{measurements.map((measurement) => <MeasurementCard key={measurement.id} measurement={measurement} onEdit={onEdit} onDelete={onDelete} />)}</div></section>; }
export function MeasurementCard({ measurement, onEdit, onDelete }: { measurement: GrowthMeasurement; onEdit: (measurement: GrowthMeasurement) => void; onDelete: (id: string) => void }) { return <article className="measurement-card"><div><time>{formatGrowthDate(measurement.date)} · {measurement.time}</time><strong>{measurement.weightKg.toFixed(2)} kg <i /> {measurement.lengthCm} cm <i /> {measurement.headCircumferenceCm} cm</strong>{measurement.note ? <p>{measurement.note}</p> : null}</div><div><button type="button" aria-label={`Edit measurement from ${formatGrowthDate(measurement.date)}`} onClick={() => onEdit(measurement)}><Pencil size={16} /></button><button type="button" aria-label={`Delete measurement from ${formatGrowthDate(measurement.date)}`} onClick={() => onDelete(measurement.id)}><Trash2 size={16} /></button></div></article>; }

export function AddMeasurementForm({ measurement, onClose, onSave }: { measurement: GrowthMeasurement | null; onClose: () => void; onSave: (draft: Omit<GrowthMeasurement, "id" | "timelineActivityId">, keepOpen: boolean) => void }) {
  const [error, setError] = useState(""); const saveAgain = useRef(false);
  const [form, setForm] = useState({ date: measurement?.date ?? "2026-07-10", time: measurement?.time ?? "10:00", weightKg: measurement?.weightKg.toString() ?? "", lengthCm: measurement?.lengthCm.toString() ?? "", headCircumferenceCm: measurement?.headCircumferenceCm.toString() ?? "", note: measurement?.note ?? "" });
  function submit(event: React.FormEvent) { event.preventDefault(); const weightKg = Number(form.weightKg); const lengthCm = Number(form.lengthCm); const headCircumferenceCm = Number(form.headCircumferenceCm); if (!form.date || !form.time || !form.weightKg || !form.lengthCm || !form.headCircumferenceCm || [weightKg, lengthCm, headCircumferenceCm].some((value) => !Number.isFinite(value) || value < 0)) { setError("Please enter a date, time and valid non-negative measurements."); return; } onSave({ date: form.date, time: form.time, weightKg, lengthCm, headCircumferenceCm, note: form.note.trim() || undefined }, saveAgain.current); if (saveAgain.current) setForm({ ...form, weightKg: "", lengthCm: "", headCircumferenceCm: "", note: "" }); }
  return <div className="development-sheet-layer"><button className="development-sheet-layer__overlay" type="button" onClick={onClose} aria-label="Close measurement form" /><section className="development-sheet" role="dialog" aria-modal="true" aria-labelledby="measurement-form-title"><header><div><p>Growth</p><h2 id="measurement-form-title">{measurement ? "Edit measurement" : "Add measurement"}</h2></div><button type="button" aria-label="Close measurement form" onClick={onClose}>×</button></header><form onSubmit={submit}><div className="development-form__grid"><label>Date<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>Time<input type="time" value={form.time} onChange={(event) => setForm({ ...form, time: event.target.value })} /></label><label>Weight (kg)<input inputMode="decimal" value={form.weightKg} onChange={(event) => setForm({ ...form, weightKg: event.target.value })} /></label><label>Length (cm)<input inputMode="decimal" value={form.lengthCm} onChange={(event) => setForm({ ...form, lengthCm: event.target.value })} /></label><label className="development-form__full">Head circumference (cm)<input inputMode="decimal" value={form.headCircumferenceCm} onChange={(event) => setForm({ ...form, headCircumferenceCm: event.target.value })} /></label><label className="development-form__full">Note <em>Optional</em><textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label></div>{error ? <p className="development-form__error">{error}</p> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>Cancel</button>{!measurement ? <button type="submit" className="button button--secondary" onClick={() => { saveAgain.current = true; }}>Save & add another</button> : null}<button type="submit" className="button button--primary" onClick={() => { saveAgain.current = false; }}>{measurement ? "Save changes" : "Save measurement"}</button></footer></form></section></div>;
}
