"use client";

import { useBabyProfile } from "@/components/baby/baby-profile-provider";
import { useDevelopment } from "@/components/development/development-provider";
import { format, useLocale } from "@/components/i18n/locale-provider";
import { formatGrowthDate, formatMeasurementValue, metricLabel, metricUnit, metricValue, sortMeasurements } from "@/lib/development-data";
import type { GrowthMeasurement, GrowthMetric } from "@/types/development";
import { CalendarDays, Pencil, Plus, Scale, Trash2 } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { GrowthChart } from "./growth-chart";

const metrics: GrowthMetric[] = ["weight", "length", "headCircumference"];

export function GrowthDashboard() {
  const { measurements, saveMeasurement, removeMeasurement } = useDevelopment();
  const { profile } = useBabyProfile();
  const { t } = useLocale();
  const dict = t((d) => d.care.growth);
  const [metric, setMetric] = useState<GrowthMetric>("weight");
  const [editing, setEditing] = useState<GrowthMeasurement | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [toast, setToast] = useState<string | null>(null);
  const ordered = useMemo(() => sortMeasurements(measurements), [measurements]);
  const latest = ordered.at(-1);
  const previous = ordered.at(-2);
  const currentValue = latest ? metricValue(latest, metric) : 0;
  const change = latest && previous ? currentValue - metricValue(previous, metric) : 0;
  function openAdd() { setEditing(null); setFormOpen(true); }
  function save(draft: Omit<GrowthMeasurement, "id" | "timelineActivityId">, keepOpen: boolean) { saveMeasurement(draft, editing?.id); setToast(editing ? dict.toasts.updated : dict.toasts.addedToTimeline); if (keepOpen) setEditing(null); else setFormOpen(false); window.setTimeout(() => setToast(null), 3200); }
  return <div className="growth-page"><header className="tracker-page__header"><p>{format(dict.subtitleTemplate, { name: profile.preferredName })}</p><h1>{dict.title}</h1></header><GrowthSummaryCard measurement={latest} onAdd={openAdd} /><section className="growth-metric-tabs" aria-label="Growth metrics">{metrics.map((item) => <button key={item} className={metric === item ? "growth-metric-tabs__button growth-metric-tabs__button--active" : "growth-metric-tabs__button"} type="button" onClick={() => setMetric(item)}>{dict.metrics[item]}</button>)}</section><section className="growth-current-metric"><span>{metricLabel(metric, dict.metricFullLabels)}</span><strong>{formatMeasurementValue(currentValue, metric)}</strong><p>{change > 0 ? format(dict.sinceLastTemplate, { change: change.toFixed(metric === "weight" ? 2 : 1), unit: metricUnit(metric) }) : dict.firstMeasurement}</p></section><GrowthChart metric={metric} measurements={ordered} /><PercentilePlaceholderCard /><GrowthHistoryList measurements={[...ordered].reverse()} onEdit={(measurement) => { setEditing(measurement); setFormOpen(true); }} onDelete={(id) => { removeMeasurement(id); setToast(dict.toasts.removed); window.setTimeout(() => setToast(null), 3200); }} />{formOpen ? <AddMeasurementForm measurement={editing} onClose={() => setFormOpen(false)} onSave={save} /> : null}{toast ? <div className="pilu-toast" role="status">{toast}</div> : null}</div>;
}

export function GrowthSummaryCard({ measurement, onAdd }: { measurement?: GrowthMeasurement; onAdd: () => void }) { const { profile } = useBabyProfile(); const { locale, t } = useLocale(); const dict = t((d) => d.care.growth.summary); return <section className="growth-summary-card"><div><p>{dict.label}</p><h2>{format(dict.headingTemplate, { name: profile.preferredName })}</h2></div><button type="button" className="button button--primary" onClick={onAdd}><Plus size={17} aria-hidden="true" />{dict.addMeasurement}</button><div className="growth-summary-card__metrics"><span><strong>{measurement?.weightKg.toFixed(2) ?? "5.10"} kg</strong>{dict.weight}</span><span><strong>{measurement?.lengthCm ?? 58} cm</strong>{dict.length}</span><span><strong>{measurement?.headCircumferenceCm ?? 38} cm</strong>{dict.headCircumference}</span></div><small><CalendarDays size={14} aria-hidden="true" />{dict.updatedPrefix} {measurement ? formatGrowthDate(measurement.date, locale) : dict.today}</small></section>; }
export function PercentilePlaceholderCard() { const { t } = useLocale(); const dict = t((d) => d.care.growth.percentile); return <section className="percentile-placeholder-card"><Scale size={21} aria-hidden="true" /><div><h2>{dict.heading}</h2><p>{dict.body}</p></div></section>; }
export function GrowthHistoryList({ measurements, onEdit, onDelete }: { measurements: GrowthMeasurement[]; onEdit: (measurement: GrowthMeasurement) => void; onDelete: (id: string) => void }) { const { t } = useLocale(); const dict = t((d) => d.care.growth.history); return <section className="growth-history"><header><div><p>{dict.label}</p><h2>{dict.heading}</h2></div></header><div>{measurements.map((measurement) => <MeasurementCard key={measurement.id} measurement={measurement} onEdit={onEdit} onDelete={onDelete} />)}</div></section>; }
export function MeasurementCard({ measurement, onEdit, onDelete }: { measurement: GrowthMeasurement; onEdit: (measurement: GrowthMeasurement) => void; onDelete: (id: string) => void }) { const { locale, t } = useLocale(); const dict = t((d) => d.care.growth.history); const dateLabel = formatGrowthDate(measurement.date, locale); return <article className="measurement-card"><div><time>{dateLabel} · {measurement.time}</time><strong>{measurement.weightKg.toFixed(2)} kg <i /> {measurement.lengthCm} cm <i /> {measurement.headCircumferenceCm} cm</strong>{measurement.note ? <p>{measurement.note}</p> : null}</div><div><button type="button" aria-label={format(dict.editAriaTemplate, { date: dateLabel })} onClick={() => onEdit(measurement)}><Pencil size={16} /></button><button type="button" aria-label={format(dict.deleteAriaTemplate, { date: dateLabel })} onClick={() => onDelete(measurement.id)}><Trash2 size={16} /></button></div></article>; }

export function AddMeasurementForm({ measurement, onClose, onSave }: { measurement: GrowthMeasurement | null; onClose: () => void; onSave: (draft: Omit<GrowthMeasurement, "id" | "timelineActivityId">, keepOpen: boolean) => void }) {
  const { t } = useLocale(); const dict = t((d) => d.care.growth.form);
  const [error, setError] = useState(""); const saveAgain = useRef(false);
  const [form, setForm] = useState({ date: measurement?.date ?? "2026-07-10", time: measurement?.time ?? "10:00", weightKg: measurement?.weightKg.toString() ?? "", lengthCm: measurement?.lengthCm.toString() ?? "", headCircumferenceCm: measurement?.headCircumferenceCm.toString() ?? "", note: measurement?.note ?? "" });
  function submit(event: React.FormEvent) { event.preventDefault(); const weightKg = Number(form.weightKg); const lengthCm = Number(form.lengthCm); const headCircumferenceCm = Number(form.headCircumferenceCm); if (!form.date || !form.time || !form.weightKg || !form.lengthCm || !form.headCircumferenceCm || [weightKg, lengthCm, headCircumferenceCm].some((value) => !Number.isFinite(value) || value < 0)) { setError(dict.validation); return; } onSave({ date: form.date, time: form.time, weightKg, lengthCm, headCircumferenceCm, note: form.note.trim() || undefined }, saveAgain.current); if (saveAgain.current) setForm({ ...form, weightKg: "", lengthCm: "", headCircumferenceCm: "", note: "" }); }
  return <div className="development-sheet-layer"><button className="development-sheet-layer__overlay" type="button" onClick={onClose} aria-label={dict.closeLabel} /><section className="development-sheet" role="dialog" aria-modal="true" aria-labelledby="measurement-form-title"><header><div><p>{dict.eyebrow}</p><h2 id="measurement-form-title">{measurement ? dict.editTitle : dict.addTitle}</h2></div><button type="button" aria-label={dict.closeLabel} onClick={onClose}>×</button></header><form onSubmit={submit}><div className="development-form__grid"><label>{dict.date}<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label><label>{dict.time}<input type="time" value={form.time} onChange={(event) => setForm({ ...form, time: event.target.value })} /></label><label>{dict.weightKg}<input inputMode="decimal" value={form.weightKg} onChange={(event) => setForm({ ...form, weightKg: event.target.value })} /></label><label>{dict.lengthCm}<input inputMode="decimal" value={form.lengthCm} onChange={(event) => setForm({ ...form, lengthCm: event.target.value })} /></label><label className="development-form__full">{dict.headCircumferenceCm}<input inputMode="decimal" value={form.headCircumferenceCm} onChange={(event) => setForm({ ...form, headCircumferenceCm: event.target.value })} /></label><label className="development-form__full">{dict.note} <em>{dict.optional}</em><textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></label></div>{error ? <p className="development-form__error">{error}</p> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>{dict.cancel}</button>{!measurement ? <button type="submit" className="button button--secondary" onClick={() => { saveAgain.current = true; }}>{dict.saveAndAddAnother}</button> : null}<button type="submit" className="button button--primary" onClick={() => { saveAgain.current = false; }}>{measurement ? dict.saveChanges : dict.saveMeasurement}</button></footer></form></section></div>;
}
