"use client";
/* eslint-disable @next/next/no-img-element -- local blob previews are not uploaded or remotely optimized. */

import { useDevelopment } from "@/components/development/development-provider";
import { useMemories } from "@/components/memory/memory-provider";
import { formatAchievementDate } from "@/lib/development-data";
import type { Milestone, MilestoneCategory, MilestoneStatus, MilestoneUpdate } from "@/types/development";
import { Baby, BookOpen, CircleDot, Heart, Images, MessageCircle, Milk, MoveRight, Sparkles, Trophy } from "lucide-react";
import { useMemo, useState } from "react";

const categories: { id: MilestoneCategory | "all"; label: string; icon: typeof Heart }[] = [
  { id: "all", label: "All", icon: Sparkles }, { id: "social", label: "Social", icon: Heart }, { id: "communication", label: "Communication", icon: MessageCircle }, { id: "movement", label: "Movement", icon: MoveRight }, { id: "learning", label: "Learning", icon: BookOpen }, { id: "feeding", label: "Feeding", icon: Milk }, { id: "firstMoments", label: "First moments", icon: Baby },
];
const statusLabels: Record<MilestoneStatus, string> = { upcoming: "Upcoming", inProgress: "In progress", achieved: "Achieved", notApplicable: "Not applicable" };

export function MilestoneDashboard() {
  const { milestones, updateMilestone } = useDevelopment(); const { memories } = useMemories();
  const [category, setCategory] = useState<MilestoneCategory | "all">("all"); const [selected, setSelected] = useState<Milestone | null>(null); const [toast, setToast] = useState<string | null>(null);
  const visible = useMemo(() => milestones.filter((milestone) => category === "all" || milestone.category === category), [milestones, category]);
  const achieved = milestones.filter((milestone) => milestone.status === "achieved"); const upcoming = milestones.filter((milestone) => milestone.status === "upcoming" || milestone.status === "inProgress"); const memoryCount = memories.filter((memory) => memory.milestoneId).length;
  function save(id: string, update: MilestoneUpdate) { updateMilestone(id, update); setSelected(null); setToast(update.status === "achieved" ? "Milestone saved" : "Milestone updated"); window.setTimeout(() => setToast(null), 3200); }
  return <div className="milestones-page"><header className="tracker-page__header"><p>Celebrate every new step</p><h1>Milestones</h1></header><MilestoneOverview achieved={achieved.length} upcoming={upcoming.length} memories={memoryCount} /><UpcomingMilestonesCard milestones={upcoming.slice(0, 3)} onSelect={setSelected} /><DevelopmentDisclaimer /><MilestoneCategoryTabs active={category} onChange={setCategory} /><section className="milestone-list" aria-label="Milestones">{visible.map((milestone) => <MilestoneCard key={milestone.id} milestone={milestone} memorySaved={memories.some((memory) => memory.milestoneId === milestone.id)} onOpen={setSelected} />)}</section>{selected ? <MilestoneDetailSheet milestone={selected} onClose={() => setSelected(null)} onSave={save} /> : null}{toast ? <div className="pilu-toast" role="status">{toast}</div> : null}</div>;
}

export function MilestoneOverview({ achieved, upcoming, memories }: { achieved: number; upcoming: number; memories: number }) { return <section className="milestone-overview"><div><Trophy size={20} aria-hidden="true" /><span><strong>{achieved}</strong>achieved</span></div><div><CircleDot size={20} aria-hidden="true" /><span><strong>{upcoming}</strong>coming up</span></div><div><Images size={20} aria-hidden="true" /><span><strong>{memories}</strong>memories</span></div></section>; }
export function MilestoneCategoryTabs({ active, onChange }: { active: MilestoneCategory | "all"; onChange: (category: MilestoneCategory | "all") => void }) { return <div className="milestone-category-tabs" role="tablist" aria-label="Milestone categories">{categories.map((category) => { const Icon = category.icon; return <button key={category.id} type="button" role="tab" aria-selected={active === category.id} className={active === category.id ? "milestone-category-tabs__button milestone-category-tabs__button--active" : "milestone-category-tabs__button"} onClick={() => onChange(category.id)}><Icon size={16} aria-hidden="true" />{category.label}</button>; })}</div>; }
export function MilestoneStatusBadge({ status }: { status: MilestoneStatus }) { return <span className={`milestone-status milestone-status--${status}`}>{statusLabels[status]}</span>; }
export function MilestoneCard({ milestone, memorySaved, onOpen }: { milestone: Milestone; memorySaved: boolean; onOpen: (milestone: Milestone) => void }) { const category = categories.find((item) => item.id === milestone.category); const Icon = category?.icon ?? Sparkles; return <article className="milestone-card"><button type="button" onClick={() => onOpen(milestone)} aria-label={`Open ${milestone.title}`}><div className="milestone-card__icon"><Icon size={20} aria-hidden="true" /></div><div><div className="milestone-card__top"><span>{category?.label}</span><MilestoneStatusBadge status={milestone.status} /></div><h2>{milestone.title}</h2><p>{milestone.status === "achieved" && milestone.achievedDate ? `Achieved ${formatAchievementDate(milestone.achievedDate)}` : milestone.typicalAge || "A gentle milestone to notice in time."}</p>{milestone.note ? <small>{milestone.note}</small> : null}</div>{memorySaved ? <Images className="milestone-card__memory" size={17} aria-label="Related memory saved" /> : null}</button></article>; }
export function UpcomingMilestonesCard({ milestones, onSelect }: { milestones: Milestone[]; onSelect: (milestone: Milestone) => void }) { return <section className="upcoming-milestones-card"><div><p>Coming up</p><h2>Little things to notice</h2><span>General examples, not predictions.</span></div><ul>{milestones.map((milestone) => <li key={milestone.id}><button type="button" onClick={() => onSelect(milestone)}>{milestone.title}<span>{milestone.status === "inProgress" ? "In progress" : "General guidance"}</span></button></li>)}</ul></section>; }
export function DevelopmentDisclaimer() { return <p className="development-disclaimer">Children develop at different speeds. Milestone information is for general guidance only.</p>; }

export function MilestoneDetailSheet({ milestone, onClose, onSave }: { milestone: Milestone; onClose: () => void; onSave: (id: string, update: MilestoneUpdate) => void }) {
  const [status, setStatus] = useState<MilestoneStatus>(milestone.status); const [date, setDate] = useState(milestone.achievedDate ?? "2026-07-10"); const [note, setNote] = useState(milestone.note ?? ""); const [imagePreview, setImagePreview] = useState(milestone.imagePreview); const [saveAsMemory, setSaveAsMemory] = useState(false);
  function handleImage(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) setImagePreview(URL.createObjectURL(file)); }
  function submit(event: React.FormEvent) { event.preventDefault(); onSave(milestone.id, { status, achievedDate: status === "achieved" ? date : undefined, note: note.trim() || undefined, imagePreview, saveAsMemory: status === "achieved" && saveAsMemory }); }
  return <div className="development-sheet-layer"><button className="development-sheet-layer__overlay" type="button" onClick={onClose} aria-label="Close milestone details" /><section className="development-sheet milestone-detail-sheet" role="dialog" aria-modal="true" aria-labelledby="milestone-detail-title"><header><div><p>Milestone</p><h2 id="milestone-detail-title">{milestone.title}</h2></div><button type="button" aria-label="Close milestone details" onClick={onClose}>×</button></header><p className="milestone-detail-sheet__description">{milestone.description}</p><form onSubmit={submit}><label>Status<select value={status} onChange={(event) => setStatus(event.target.value as MilestoneStatus)} aria-label="Milestone status">{(Object.keys(statusLabels) as MilestoneStatus[]).map((item) => <option key={item} value={item}>{statusLabels[item]}</option>)}</select></label>{status === "achieved" ? <label>Date achieved<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label> : null}<label>Note <em>Optional</em><textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><label>Local photo preview <em>Optional, not uploaded</em><input type="file" accept="image/*" onChange={handleImage} /></label>{imagePreview ? <><span className="sr-only">Local image preview selected</span>{/* A blob URL is local-only and deliberately bypasses remote image optimization. */}<img className="milestone-detail-sheet__preview" src={imagePreview} alt="Local milestone preview" /></> : null}{status === "achieved" && !milestone.memoryActivityId ? <label className="development-check"><input type="checkbox" checked={saveAsMemory} onChange={(event) => setSaveAsMemory(event.target.checked)} />Save as memory in Timeline</label> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>Cancel</button><button type="submit" className="button button--primary">Save milestone</button></footer></form></section></div>;
}
