"use client";
/* eslint-disable @next/next/no-img-element -- local blob previews are not uploaded or remotely optimized. */

import { useDevelopment } from "@/components/development/development-provider";
import { format, useLocale } from "@/components/i18n/locale-provider";
import { useMemories } from "@/components/memory/memory-provider";
import { formatAchievementDate } from "@/lib/development-data";
import type { Dictionary } from "@/lib/i18n/dictionary";
import type { Milestone, MilestoneCategory, MilestoneStatus, MilestoneUpdate } from "@/types/development";
import { Baby, BookOpen, CircleDot, Heart, Images, MessageCircle, Milk, MoveRight, Sparkles, Trophy } from "lucide-react";
import { useMemo, useState } from "react";

const categoryIcons: Record<MilestoneCategory | "all", typeof Heart> = { all: Sparkles, social: Heart, communication: MessageCircle, movement: MoveRight, learning: BookOpen, feeding: Milk, firstMoments: Baby };
const categoryIds: (MilestoneCategory | "all")[] = ["all", "social", "communication", "movement", "learning", "feeding", "firstMoments"];

function itemCopy(dict: Dictionary["milestones"], milestone: Milestone) {
  return dict.items[milestone.id] ?? { title: milestone.title, description: milestone.description, typicalAge: milestone.typicalAge };
}

export function MilestoneDashboard() {
  const { milestones, updateMilestone } = useDevelopment(); const { memories } = useMemories();
  const { t } = useLocale(); const dict = t((d) => d.milestones);
  const [category, setCategory] = useState<MilestoneCategory | "all">("all"); const [selected, setSelected] = useState<Milestone | null>(null); const [toast, setToast] = useState<string | null>(null);
  const visible = useMemo(() => milestones.filter((milestone) => category === "all" || milestone.category === category), [milestones, category]);
  const achieved = milestones.filter((milestone) => milestone.status === "achieved"); const upcoming = milestones.filter((milestone) => milestone.status === "upcoming" || milestone.status === "inProgress"); const memoryCount = memories.filter((memory) => memory.milestoneId).length;
  function save(id: string, update: MilestoneUpdate) { updateMilestone(id, update); setSelected(null); setToast(update.status === "achieved" ? dict.toasts.saved : dict.toasts.updated); window.setTimeout(() => setToast(null), 3200); }
  return <div className="milestones-page"><header className="tracker-page__header"><p>{dict.subtitle}</p><h1>{dict.title}</h1></header><MilestoneOverview achieved={achieved.length} upcoming={upcoming.length} memories={memoryCount} /><UpcomingMilestonesCard milestones={upcoming.slice(0, 3)} onSelect={setSelected} /><DevelopmentDisclaimer /><MilestoneCategoryTabs active={category} onChange={setCategory} /><section className="milestone-list" aria-label="Milestones">{visible.map((milestone) => <MilestoneCard key={milestone.id} milestone={milestone} memorySaved={memories.some((memory) => memory.milestoneId === milestone.id)} onOpen={setSelected} />)}</section>{selected ? <MilestoneDetailSheet milestone={selected} onClose={() => setSelected(null)} onSave={save} /> : null}{toast ? <div className="pilu-toast" role="status">{toast}</div> : null}</div>;
}

export function MilestoneOverview({ achieved, upcoming, memories }: { achieved: number; upcoming: number; memories: number }) { const { t } = useLocale(); const dict = t((d) => d.milestones.overview); return <section className="milestone-overview"><div><Trophy size={20} aria-hidden="true" /><span><strong>{achieved}</strong>{dict.achieved}</span></div><div><CircleDot size={20} aria-hidden="true" /><span><strong>{upcoming}</strong>{dict.comingUp}</span></div><div><Images size={20} aria-hidden="true" /><span><strong>{memories}</strong>{dict.memories}</span></div></section>; }
export function MilestoneCategoryTabs({ active, onChange }: { active: MilestoneCategory | "all"; onChange: (category: MilestoneCategory | "all") => void }) { const { t } = useLocale(); const dict = t((d) => d.milestones.categories); return <div className="milestone-category-tabs" role="tablist" aria-label="Milestone categories">{categoryIds.map((id) => { const Icon = categoryIcons[id]; return <button key={id} type="button" role="tab" aria-selected={active === id} className={active === id ? "milestone-category-tabs__button milestone-category-tabs__button--active" : "milestone-category-tabs__button"} onClick={() => onChange(id)}><Icon size={16} aria-hidden="true" />{dict[id]}</button>; })}</div>; }
export function MilestoneStatusBadge({ status }: { status: MilestoneStatus }) { const { t } = useLocale(); const statuses = t((d) => d.milestones.statuses); return <span className={`milestone-status milestone-status--${status}`}>{statuses[status]}</span>; }
export function MilestoneCard({ milestone, memorySaved, onOpen }: { milestone: Milestone; memorySaved: boolean; onOpen: (milestone: Milestone) => void }) { const { locale, t } = useLocale(); const dict = t((d) => d.milestones); const categoryDict = t((d) => d.milestones.categories); const copy = itemCopy(dict, milestone); const Icon = categoryIcons[milestone.category] ?? Sparkles; return <article className="milestone-card"><button type="button" onClick={() => onOpen(milestone)} aria-label={format(dict.card.openAriaTemplate, { title: copy.title })}><div className="milestone-card__icon"><Icon size={20} aria-hidden="true" /></div><div><div className="milestone-card__top"><span>{categoryDict[milestone.category]}</span><MilestoneStatusBadge status={milestone.status} /></div><h2>{copy.title}</h2><p>{milestone.status === "achieved" && milestone.achievedDate ? format(dict.card.achievedTemplate, { date: formatAchievementDate(milestone.achievedDate, locale) }) : copy.typicalAge || dict.card.gentleMilestone}</p>{milestone.note ? <small>{milestone.note}</small> : null}</div>{memorySaved ? <Images className="milestone-card__memory" size={17} aria-label={dict.card.relatedMemorySaved} /> : null}</button></article>; }
export function UpcomingMilestonesCard({ milestones, onSelect }: { milestones: Milestone[]; onSelect: (milestone: Milestone) => void }) { const { t } = useLocale(); const dict = t((d) => d.milestones); const upcomingDict = t((d) => d.milestones.upcomingCard); return <section className="upcoming-milestones-card"><div><p>{upcomingDict.label}</p><h2>{upcomingDict.heading}</h2><span>{upcomingDict.note}</span></div><ul>{milestones.map((milestone) => { const copy = itemCopy(dict, milestone); return <li key={milestone.id}><button type="button" onClick={() => onSelect(milestone)}>{copy.title}<span>{milestone.status === "inProgress" ? dict.statuses.inProgress : upcomingDict.generalGuidance}</span></button></li>; })}</ul></section>; }
export function DevelopmentDisclaimer() { const { t } = useLocale(); return <p className="development-disclaimer">{t((d) => d.milestones.disclaimer)}</p>; }

export function MilestoneDetailSheet({ milestone, onClose, onSave }: { milestone: Milestone; onClose: () => void; onSave: (id: string, update: MilestoneUpdate) => void }) {
  const { t } = useLocale(); const dict = t((d) => d.milestones); const detailDict = t((d) => d.milestones.detail); const statuses = t((d) => d.milestones.statuses);
  const copy = itemCopy(dict, milestone);
  const [status, setStatus] = useState<MilestoneStatus>(milestone.status); const [date, setDate] = useState(milestone.achievedDate ?? "2026-07-10"); const [note, setNote] = useState(milestone.note ?? ""); const [imagePreview, setImagePreview] = useState(milestone.imagePreview); const [saveAsMemory, setSaveAsMemory] = useState(false);
  function handleImage(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) setImagePreview(URL.createObjectURL(file)); }
  function submit(event: React.FormEvent) { event.preventDefault(); onSave(milestone.id, { status, achievedDate: status === "achieved" ? date : undefined, note: note.trim() || undefined, imagePreview, saveAsMemory: status === "achieved" && saveAsMemory }); }
  return <div className="development-sheet-layer"><button className="development-sheet-layer__overlay" type="button" onClick={onClose} aria-label={detailDict.closeLabel} /><section className="development-sheet milestone-detail-sheet" role="dialog" aria-modal="true" aria-labelledby="milestone-detail-title"><header><div><p>{detailDict.eyebrow}</p><h2 id="milestone-detail-title">{copy.title}</h2></div><button type="button" aria-label={detailDict.closeLabel} onClick={onClose}>×</button></header><p className="milestone-detail-sheet__description">{copy.description}</p><form onSubmit={submit}><label>{detailDict.statusLabel}<select value={status} onChange={(event) => setStatus(event.target.value as MilestoneStatus)} aria-label={detailDict.statusLabel}>{(Object.keys(statuses) as MilestoneStatus[]).map((item) => <option key={item} value={item}>{statuses[item]}</option>)}</select></label>{status === "achieved" ? <label>{detailDict.dateAchieved}<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label> : null}<label>{detailDict.note} <em>{detailDict.optional}</em><textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><label>{detailDict.localPhotoPreview} <em>{detailDict.notUploaded}</em><input type="file" accept="image/*" onChange={handleImage} /></label>{imagePreview ? <><span className="sr-only">{detailDict.localImagePreviewSelected}</span>{/* A blob URL is local-only and deliberately bypasses remote image optimization. */}<img className="milestone-detail-sheet__preview" src={imagePreview} alt={detailDict.localImagePreviewAlt} /></> : null}{status === "achieved" && !milestone.memoryActivityId ? <label className="development-check"><input type="checkbox" checked={saveAsMemory} onChange={(event) => setSaveAsMemory(event.target.checked)} />{detailDict.saveAsMemory}</label> : null}<footer><button type="button" className="button button--secondary" onClick={onClose}>{detailDict.cancel}</button><button type="submit" className="button button--primary">{detailDict.save}</button></footer></form></section></div>;
}
